package com.expocms.server.db.model;

import java.util.Date;

public class RdActivitygiftStat {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_activitygift_stat.ids
     *
     * @mbggenerated Sun Oct 04 14:55:06 CST 2015
     */
    private String ids;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_activitygift_stat.activityName
     *
     * @mbggenerated Sun Oct 04 14:55:06 CST 2015
     */
    private String activityname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_activitygift_stat.createDate
     *
     * @mbggenerated Sun Oct 04 14:55:06 CST 2015
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_activitygift_stat.count
     *
     * @mbggenerated Sun Oct 04 14:55:06 CST 2015
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_activitygift_stat.value
     *
     * @mbggenerated Sun Oct 04 14:55:06 CST 2015
     */
    private Long value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_activitygift_stat.activeCount
     *
     * @mbggenerated Sun Oct 04 14:55:06 CST 2015
     */
    private Integer activecount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_activitygift_stat.usedCount
     *
     * @mbggenerated Sun Oct 04 14:55:06 CST 2015
     */
    private Integer usedcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_activitygift_stat.expireDays
     *
     * @mbggenerated Sun Oct 04 14:55:06 CST 2015
     */
    private Integer expiredays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_activitygift_stat.activateDays
     *
     * @mbggenerated Sun Oct 04 14:55:06 CST 2015
     */
    private Integer activatedays;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_activitygift_stat.ids
     *
     * @return the value of rd_activitygift_stat.ids
     *
     * @mbggenerated Sun Oct 04 14:55:06 CST 2015
     */
    public String getIds() {
        return ids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_activitygift_stat.ids
     *
     * @param ids the value for rd_activitygift_stat.ids
     *
     * @mbggenerated Sun Oct 04 14:55:06 CST 2015
     */
    public void setIds(String ids) {
        this.ids = ids == null ? null : ids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_activitygift_stat.activityName
     *
     * @return the value of rd_activitygift_stat.activityName
     *
     * @mbggenerated Sun Oct 04 14:55:06 CST 2015
     */
    public String getActivityname() {
        return activityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_activitygift_stat.activityName
     *
     * @param activityname the value for rd_activitygift_stat.activityName
     *
     * @mbggenerated Sun Oct 04 14:55:06 CST 2015
     */
    public void setActivityname(String activityname) {
        this.activityname = activityname == null ? null : activityname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_activitygift_stat.createDate
     *
     * @return the value of rd_activitygift_stat.createDate
     *
     * @mbggenerated Sun Oct 04 14:55:06 CST 2015
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_activitygift_stat.createDate
     *
     * @param createdate the value for rd_activitygift_stat.createDate
     *
     * @mbggenerated Sun Oct 04 14:55:06 CST 2015
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_activitygift_stat.count
     *
     * @return the value of rd_activitygift_stat.count
     *
     * @mbggenerated Sun Oct 04 14:55:06 CST 2015
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_activitygift_stat.count
     *
     * @param count the value for rd_activitygift_stat.count
     *
     * @mbggenerated Sun Oct 04 14:55:06 CST 2015
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_activitygift_stat.value
     *
     * @return the value of rd_activitygift_stat.value
     *
     * @mbggenerated Sun Oct 04 14:55:06 CST 2015
     */
    public Long getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_activitygift_stat.value
     *
     * @param value the value for rd_activitygift_stat.value
     *
     * @mbggenerated Sun Oct 04 14:55:06 CST 2015
     */
    public void setValue(Long value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_activitygift_stat.activeCount
     *
     * @return the value of rd_activitygift_stat.activeCount
     *
     * @mbggenerated Sun Oct 04 14:55:06 CST 2015
     */
    public Integer getActivecount() {
        return activecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_activitygift_stat.activeCount
     *
     * @param activecount the value for rd_activitygift_stat.activeCount
     *
     * @mbggenerated Sun Oct 04 14:55:06 CST 2015
     */
    public void setActivecount(Integer activecount) {
        this.activecount = activecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_activitygift_stat.usedCount
     *
     * @return the value of rd_activitygift_stat.usedCount
     *
     * @mbggenerated Sun Oct 04 14:55:06 CST 2015
     */
    public Integer getUsedcount() {
        return usedcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_activitygift_stat.usedCount
     *
     * @param usedcount the value for rd_activitygift_stat.usedCount
     *
     * @mbggenerated Sun Oct 04 14:55:06 CST 2015
     */
    public void setUsedcount(Integer usedcount) {
        this.usedcount = usedcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_activitygift_stat.expireDays
     *
     * @return the value of rd_activitygift_stat.expireDays
     *
     * @mbggenerated Sun Oct 04 14:55:06 CST 2015
     */
    public Integer getExpiredays() {
        return expiredays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_activitygift_stat.expireDays
     *
     * @param expiredays the value for rd_activitygift_stat.expireDays
     *
     * @mbggenerated Sun Oct 04 14:55:06 CST 2015
     */
    public void setExpiredays(Integer expiredays) {
        this.expiredays = expiredays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_activitygift_stat.activateDays
     *
     * @return the value of rd_activitygift_stat.activateDays
     *
     * @mbggenerated Sun Oct 04 14:55:06 CST 2015
     */
    public Integer getActivatedays() {
        return activatedays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_activitygift_stat.activateDays
     *
     * @param activatedays the value for rd_activitygift_stat.activateDays
     *
     * @mbggenerated Sun Oct 04 14:55:06 CST 2015
     */
    public void setActivatedays(Integer activatedays) {
        this.activatedays = activatedays;
    }
}