package com.expocms.server.db.model;

import java.util.Date;

public class RdActivity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_activity.ids
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String ids;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_activity.activityName
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String activityname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_activity.createDate
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_activity.count
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Integer count;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_activity.ids
     *
     * @return the value of rd_activity.ids
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getIds() {
        return ids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_activity.ids
     *
     * @param ids the value for rd_activity.ids
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setIds(String ids) {
        this.ids = ids == null ? null : ids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_activity.activityName
     *
     * @return the value of rd_activity.activityName
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getActivityname() {
        return activityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_activity.activityName
     *
     * @param activityname the value for rd_activity.activityName
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setActivityname(String activityname) {
        this.activityname = activityname == null ? null : activityname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_activity.createDate
     *
     * @return the value of rd_activity.createDate
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_activity.createDate
     *
     * @param createdate the value for rd_activity.createDate
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_activity.count
     *
     * @return the value of rd_activity.count
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_activity.count
     *
     * @param count the value for rd_activity.count
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setCount(Integer count) {
        this.count = count;
    }
}