package com.expocms.server.db.model;

public class RdAdvertisement {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_advertisement.ids
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String ids;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_advertisement.content
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_advertisement.url
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_advertisement.image
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_advertisement.hidden
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Integer hidden;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_advertisement.ids
     *
     * @return the value of rd_advertisement.ids
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getIds() {
        return ids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_advertisement.ids
     *
     * @param ids the value for rd_advertisement.ids
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setIds(String ids) {
        this.ids = ids == null ? null : ids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_advertisement.content
     *
     * @return the value of rd_advertisement.content
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_advertisement.content
     *
     * @param content the value for rd_advertisement.content
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_advertisement.url
     *
     * @return the value of rd_advertisement.url
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_advertisement.url
     *
     * @param url the value for rd_advertisement.url
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_advertisement.image
     *
     * @return the value of rd_advertisement.image
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_advertisement.image
     *
     * @param image the value for rd_advertisement.image
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_advertisement.hidden
     *
     * @return the value of rd_advertisement.hidden
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Integer getHidden() {
        return hidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_advertisement.hidden
     *
     * @param hidden the value for rd_advertisement.hidden
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setHidden(Integer hidden) {
        this.hidden = hidden;
    }
}