package com.expocms.server.db.model;

public class RdAppuserinformationmodlogWithBLOBs extends RdAppuserinformationmodlog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_appuserinformationmodlog.oldBankName
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String oldbankname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_appuserinformationmodlog.newBankName
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String newbankname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_appuserinformationmodlog.oldBankName
     *
     * @return the value of rd_appuserinformationmodlog.oldBankName
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getOldbankname() {
        return oldbankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_appuserinformationmodlog.oldBankName
     *
     * @param oldbankname the value for rd_appuserinformationmodlog.oldBankName
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setOldbankname(String oldbankname) {
        this.oldbankname = oldbankname == null ? null : oldbankname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_appuserinformationmodlog.newBankName
     *
     * @return the value of rd_appuserinformationmodlog.newBankName
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getNewbankname() {
        return newbankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_appuserinformationmodlog.newBankName
     *
     * @param newbankname the value for rd_appuserinformationmodlog.newBankName
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setNewbankname(String newbankname) {
        this.newbankname = newbankname == null ? null : newbankname.trim();
    }
}