package com.expocms.server.db.model;

import java.util.Date;

public class RdAppuserOrders {
	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_appuser_orders.ids
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String ids;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_appuser_orders.ids_user
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String idsUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_appuser_orders.ids_product
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String idsProduct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_appuser_orders.amount
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Integer amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_appuser_orders.ids_payment
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String idsPayment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_appuser_orders.createtime
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_appuser_orders.bonus_amount
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Integer bonusAmount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_appuser_orders.ids
     *
     * @return the value of rd_appuser_orders.ids
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getIds() {
        return ids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_appuser_orders.ids
     *
     * @param ids the value for rd_appuser_orders.ids
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setIds(String ids) {
        this.ids = ids == null ? null : ids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_appuser_orders.ids_user
     *
     * @return the value of rd_appuser_orders.ids_user
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getIdsUser() {
        return idsUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_appuser_orders.ids_user
     *
     * @param idsUser the value for rd_appuser_orders.ids_user
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setIdsUser(String idsUser) {
        this.idsUser = idsUser == null ? null : idsUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_appuser_orders.ids_product
     *
     * @return the value of rd_appuser_orders.ids_product
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getIdsProduct() {
        return idsProduct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_appuser_orders.ids_product
     *
     * @param idsProduct the value for rd_appuser_orders.ids_product
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setIdsProduct(String idsProduct) {
        this.idsProduct = idsProduct == null ? null : idsProduct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_appuser_orders.amount
     *
     * @return the value of rd_appuser_orders.amount
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_appuser_orders.amount
     *
     * @param amount the value for rd_appuser_orders.amount
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_appuser_orders.ids_payment
     *
     * @return the value of rd_appuser_orders.ids_payment
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getIdsPayment() {
        return idsPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_appuser_orders.ids_payment
     *
     * @param idsPayment the value for rd_appuser_orders.ids_payment
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setIdsPayment(String idsPayment) {
        this.idsPayment = idsPayment == null ? null : idsPayment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_appuser_orders.createtime
     *
     * @return the value of rd_appuser_orders.createtime
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_appuser_orders.createtime
     *
     * @param createtime the value for rd_appuser_orders.createtime
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_appuser_orders.bonus_amount
     *
     * @return the value of rd_appuser_orders.bonus_amount
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Integer getBonusAmount() {
        return bonusAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_appuser_orders.bonus_amount
     *
     * @param bonusAmount the value for rd_appuser_orders.bonus_amount
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setBonusAmount(Integer bonusAmount) {
        this.bonusAmount = bonusAmount;
    }
}