package com.expocms.server.db.model;

public class RdAppuserBonus {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_appuser_bonus.ids
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String ids;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_appuser_bonus.ids_appuser
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String idsAppuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_appuser_bonus.ids_bonus
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String idsBonus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_appuser_bonus.ids_appuser_orders
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String idsAppuserOrders;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_appuser_bonus.status
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_appuser_bonus.ids
     *
     * @return the value of rd_appuser_bonus.ids
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getIds() {
        return ids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_appuser_bonus.ids
     *
     * @param ids the value for rd_appuser_bonus.ids
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setIds(String ids) {
        this.ids = ids == null ? null : ids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_appuser_bonus.ids_appuser
     *
     * @return the value of rd_appuser_bonus.ids_appuser
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getIdsAppuser() {
        return idsAppuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_appuser_bonus.ids_appuser
     *
     * @param idsAppuser the value for rd_appuser_bonus.ids_appuser
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setIdsAppuser(String idsAppuser) {
        this.idsAppuser = idsAppuser == null ? null : idsAppuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_appuser_bonus.ids_bonus
     *
     * @return the value of rd_appuser_bonus.ids_bonus
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getIdsBonus() {
        return idsBonus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_appuser_bonus.ids_bonus
     *
     * @param idsBonus the value for rd_appuser_bonus.ids_bonus
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setIdsBonus(String idsBonus) {
        this.idsBonus = idsBonus == null ? null : idsBonus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_appuser_bonus.ids_appuser_orders
     *
     * @return the value of rd_appuser_bonus.ids_appuser_orders
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getIdsAppuserOrders() {
        return idsAppuserOrders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_appuser_bonus.ids_appuser_orders
     *
     * @param idsAppuserOrders the value for rd_appuser_bonus.ids_appuser_orders
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setIdsAppuserOrders(String idsAppuserOrders) {
        this.idsAppuserOrders = idsAppuserOrders == null ? null : idsAppuserOrders.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_appuser_bonus.status
     *
     * @return the value of rd_appuser_bonus.status
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_appuser_bonus.status
     *
     * @param status the value for rd_appuser_bonus.status
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}