package com.expocms.server.db.model;

import java.io.Serializable;
import java.util.Date;

public class RdAppuser implements Serializable {

    private static final long serialVersionUID = 6239066038218207441L;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * rd_appuser.ids
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String ids;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * rd_appuser.no
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String no;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * rd_appuser.userName
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String username;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * rd_appuser.sex
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String sex;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * rd_appuser.phone
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String phone;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * rd_appuser.idcard
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String idcard;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * rd_appuser.lastTransferTime
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Date lasttransfertime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * rd_appuser.lastTransferOrderId
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String lasttransferorderid;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * rd_appuser.bankCardNo
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String bankcardno;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * rd_appuser.isBlock
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Boolean isblock;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * rd_appuser.lastTransferOrderNo
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String lasttransferorderno;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * rd_appuser.bankName
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String bankname;
    private String issuer;
    private String supportPhone;
    private String payPhone;
	private String tradingPwd;
    private String pwd;
    private Long bankQuota;
    private String cardHolder;
    private Long totalAssets;
    private String fixedgift;
    private String activitygift;
    private String token;
    private int purchaseNum;
    private Integer isBankModified;
    
    /**
     * used for password blocking purpose.
     * @return
     */
    private Integer blockCount;
    private Date blockTime;
    private Date unblockDate;

	/**
     * used for recommend.
     * @return
     */
    private String recommendCode;
	private Long commission;


	public String getIssuer () {
        return issuer;
    }
    public void setIssuer (final String issuer) {
        this.issuer = issuer;
    }

    public String getSupportPhone () {
        return supportPhone;
    }
    public void setSupportPhone (final String supportPhone) {
        this.supportPhone = supportPhone;
    }

    public String getPayPhone() {
		return payPhone;
	}
	public void setPayPhone(String payPhone) {
		this.payPhone = payPhone;
	}

    public String getPwd () {
        return pwd;
    }
    public void setPwd (final String pwd) {
        this.pwd = pwd;
    }

    public Long getBankQuota () {
        return bankQuota;
    }
    public void setBankQuota (final Long bankQuota) {
        this.bankQuota = bankQuota;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column rd_appuser.ids
     *
     * @return the value of rd_appuser.ids
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getIds () {
        return ids;
    }
    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column rd_appuser.ids
     *
     * @param ids the value for rd_appuser.ids
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setIds (final String ids) {
        this.ids = ids == null ? null : ids.trim ();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column rd_appuser.no
     *
     * @return the value of rd_appuser.no
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getNo () {
        return no;
    }
    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column rd_appuser.no
     *
     * @param no the value for rd_appuser.no
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setNo (final String no) {
        this.no = no == null ? null : no.trim ();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column rd_appuser.userName
     *
     * @return the value of rd_appuser.userName
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getUsername () {
        return username;
    }
    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column rd_appuser.userName
     *
     * @param username the value for rd_appuser.userName
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setUsername (final String username) {
        this.username = username == null ? null : username.trim ();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column rd_appuser.sex
     *
     * @return the value of rd_appuser.sex
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getSex () {
        return sex;
    }
    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column rd_appuser.sex
     *
     * @param sex the value for rd_appuser.sex
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setSex (final String sex) {
        this.sex = sex == null ? null : sex.trim ();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column rd_appuser.phone
     *
     * @return the value of rd_appuser.phone
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getPhone () {
        return phone;
    }
    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column rd_appuser.phone
     *
     * @param phone the value for rd_appuser.phone
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setPhone (final String phone) {
        this.phone = phone == null ? null : phone.trim ();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column rd_appuser.idcard
     *
     * @return the value of rd_appuser.idcard
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getIdcard () {
        return idcard;
    }
    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column rd_appuser.idcard
     *
     * @param idcard the value for rd_appuser.idcard
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setIdcard (final String idcard) {
        this.idcard = idcard == null ? null : idcard.trim ();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column rd_appuser.lastTransferTime
     *
     * @return the value of rd_appuser.lastTransferTime
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Date getLasttransfertime () {
        return lasttransfertime;
    }
    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column rd_appuser.lastTransferTime
     *
     * @param lasttransfertime the value for rd_appuser.lastTransferTime
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setLasttransfertime (final Date lasttransfertime) {
        this.lasttransfertime = lasttransfertime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column rd_appuser.lastTransferOrderId
     *
     * @return the value of rd_appuser.lastTransferOrderId
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getLasttransferorderid () {
        return lasttransferorderid;
    }
    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column rd_appuser.lastTransferOrderId
     *
     * @param lasttransferorderid the value for rd_appuser.lastTransferOrderId
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setLasttransferorderid (final String lasttransferorderid) {
        this.lasttransferorderid = lasttransferorderid == null ? null : lasttransferorderid.trim ();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column rd_appuser.bankCardNo
     *
     * @return the value of rd_appuser.bankCardNo
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getBankcardno () {
        return bankcardno;
    }
    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column rd_appuser.bankCardNo
     *
     * @param bankcardno the value for rd_appuser.bankCardNo
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setBankcardno (final String bankcardno) {
        this.bankcardno = bankcardno == null ? null : bankcardno.trim ();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column rd_appuser.isBlock
     *
     * @return the value of rd_appuser.isBlock
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Boolean getIsblock () {
        return isblock;
    }
    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column rd_appuser.isBlock
     *
     * @param isblock the value for rd_appuser.isBlock
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setIsblock (final Boolean isblock) {
        this.isblock = isblock;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column rd_appuser.lastTransferOrderNo
     *
     * @return the value of rd_appuser.lastTransferOrderNo
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getLasttransferorderno () {
        return lasttransferorderno;
    }
    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column rd_appuser.lastTransferOrderNo
     *
     * @param lasttransferorderno the value for rd_appuser.lastTransferOrderNo
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setLasttransferorderno (final String lasttransferorderno) {
        this.lasttransferorderno = lasttransferorderno == null ? null : lasttransferorderno.trim ();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column rd_appuser.bankName
     *
     * @return the value of rd_appuser.bankName
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getBankname () {
        return bankname;
    }
    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column rd_appuser.bankName
     *
     * @param bankname the value for rd_appuser.bankName
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setBankname (final String bankname) {
        this.bankname = bankname == null ? null : bankname.trim ();
    }

    public String getTradingPwd () {
        return tradingPwd;
    }
    public void setTradingPwd (final String tradingPwd) {
        this.tradingPwd = tradingPwd;
    }

    public String getCardHolder () {
        return cardHolder;
    }
    public void setCardHolder (final String cardHolder) {
        this.cardHolder = cardHolder;
    }
    
    public Long getTotalAssets() {
    	return totalAssets;
    }
    public void setTotalAssets (final Long totalAssets) {
    	this.totalAssets = totalAssets;
    }

    public String getFixedgift () {
        return fixedgift;
    }
    public void setFixedgift (final String fixedgift) {
        this.fixedgift = fixedgift;
    }

    public String getActivitygift () {
        return activitygift;
    }
    public void setActivitygift (final String activitygift) {
        this.activitygift = activitygift;
    }

    public String getToken () {
        return token;
    }
    public void setToken (final String token) {
        this.token = token;
    }

    /**
     * @return the purchaseNum
     */
    public int getPurchaseNum () {
        return purchaseNum;
    }
    /**
     * @param purchaseNum the purchaseNum to set
     */
    public void setPurchaseNum (final int purchaseNum) {
        this.purchaseNum = purchaseNum;
    }
    
    public boolean isBankModified() {
    	return isBankModified != null && isBankModified != 0;
    }
    public Integer getIsBankModified() {
		return isBankModified;
	}
	public void setIsBankModified(Integer isBankModified) {
		this.isBankModified = isBankModified;
	}
	
	/**
	 * begin.
     * used for password blocking purpose.
     * @return
     */
	public Integer getBlockCount() {
		return blockCount;
	}
	public void setBlockCount(Integer blockCount) {
		this.blockCount = blockCount;
	}
	
	public Date getBlockTime() {
		return blockTime;
	}
	public void setBlockTime(Date blockTime) {
		this.blockTime = blockTime;
	}
	
	public Date getUnblockDate() {
		return unblockDate;
	}
	public void setUnblockDate(Date unblockDate) {
		this.unblockDate = unblockDate;
	}
	/**
	 * end.
     * used for password blocking purpose.
     * @return
     */

	/**
	 * begin.
     * used for recommend.
     * @return
     */
	public String getRecommendCode() {
		return recommendCode;
	}
	public void setRecommendCode(String recommendCode) {
		this.recommendCode = recommendCode;
	}
	
	public Long getCommission() {
		return commission;
	}
	public void setCommission(Long commission) {
		this.commission = commission;
	}
	/**
	 * end.
     * used for recommend.
     * @return
     */
	
}
