package com.expocms.server.db.model;

import java.util.Date;

public class RdConsultant {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_consultant.ids
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String ids;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_consultant.type
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_consultant.time
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_consultant.operatorUserId
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String operatoruserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_consultant.operatorUserName
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String operatorusername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_consultant.title
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_consultant.content
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_consultant.ids
     *
     * @return the value of rd_consultant.ids
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getIds() {
        return ids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_consultant.ids
     *
     * @param ids the value for rd_consultant.ids
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setIds(String ids) {
        this.ids = ids == null ? null : ids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_consultant.type
     *
     * @return the value of rd_consultant.type
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_consultant.type
     *
     * @param type the value for rd_consultant.type
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_consultant.time
     *
     * @return the value of rd_consultant.time
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_consultant.time
     *
     * @param time the value for rd_consultant.time
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_consultant.operatorUserId
     *
     * @return the value of rd_consultant.operatorUserId
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getOperatoruserid() {
        return operatoruserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_consultant.operatorUserId
     *
     * @param operatoruserid the value for rd_consultant.operatorUserId
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setOperatoruserid(String operatoruserid) {
        this.operatoruserid = operatoruserid == null ? null : operatoruserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_consultant.operatorUserName
     *
     * @return the value of rd_consultant.operatorUserName
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getOperatorusername() {
        return operatorusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_consultant.operatorUserName
     *
     * @param operatorusername the value for rd_consultant.operatorUserName
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setOperatorusername(String operatorusername) {
        this.operatorusername = operatorusername == null ? null : operatorusername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_consultant.title
     *
     * @return the value of rd_consultant.title
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_consultant.title
     *
     * @param title the value for rd_consultant.title
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_consultant.content
     *
     * @return the value of rd_consultant.content
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_consultant.content
     *
     * @param content the value for rd_consultant.content
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}