package com.expocms.server.db.model;

public class RdHelpCenter {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_help_center.ids
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String ids;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_help_center.question
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String question;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_help_center.answer
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String answer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_help_center.question_id
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Long questionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_help_center.ids
     *
     * @return the value of rd_help_center.ids
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getIds() {
        return ids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_help_center.ids
     *
     * @param ids the value for rd_help_center.ids
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setIds(String ids) {
        this.ids = ids == null ? null : ids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_help_center.question
     *
     * @return the value of rd_help_center.question
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getQuestion() {
        return question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_help_center.question
     *
     * @param question the value for rd_help_center.question
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setQuestion(String question) {
        this.question = question == null ? null : question.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_help_center.answer
     *
     * @return the value of rd_help_center.answer
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_help_center.answer
     *
     * @param answer the value for rd_help_center.answer
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_help_center.question_id
     *
     * @return the value of rd_help_center.question_id
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Long getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_help_center.question_id
     *
     * @param questionId the value for rd_help_center.question_id
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setQuestionId(Long questionId) {
        this.questionId = questionId;
    }
}