package com.expocms.server.db.model;

import java.io.Serializable;
import java.util.Date;

public class RdLoanAgreement implements Serializable {

	private static final long serialVersionUID = -2618115163790457357L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_loan_agreement.ids
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String ids;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_loan_agreement.no
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String no;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_loan_agreement.createDateTime
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Date createdatetime;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_loan_agreement.userID
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String userid;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_loan_agreement.debiterName
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String debitername;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_loan_agreement.debiterIdentity
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String debiteridentity;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_loan_agreement.debiterQualifierType
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String debiterqualifiertype;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_loan_agreement.debitPurpose
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String debitpurpose;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_loan_agreement.paybackStartDate
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Date paybackstartdate;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_loan_agreement.debitAmount
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Long debitamount;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_loan_agreement.debitDuration
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Integer debitduration;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_loan_agreement.productNum
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Integer productnum;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_loan_agreement.deptMethod
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String deptmethod;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_loan_agreement.finished
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Integer finished;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_loan_agreement.restMoneyDays
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Long restmoneydays;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_loan_agreement.totalMoneyDays
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Long totalmoneydays;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_loan_agreement.debiterQualifierTypeId
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String loanNumber;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_loan_agreement.debitPurposeId
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Long restDebitAmount;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_loan_agreement.deptMethodId
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Integer restDebitDuration;
    private String projectSource;
    private String briefContent;


	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_loan_agreement.ids
     *
     * @return the value of rd_loan_agreement.ids
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getIds() {
        return ids;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_loan_agreement.ids
     *
     * @param ids the value for rd_loan_agreement.ids
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setIds(String ids) {
        this.ids = ids == null ? null : ids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_loan_agreement.no
     *
     * @return the value of rd_loan_agreement.no
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getNo() {
        return no;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_loan_agreement.no
     *
     * @param no the value for rd_loan_agreement.no
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setNo(String no) {
        this.no = no == null ? null : no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_loan_agreement.createDateTime
     *
     * @return the value of rd_loan_agreement.createDateTime
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Date getCreatedatetime() {
        return createdatetime;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_loan_agreement.createDateTime
     *
     * @param createdatetime the value for rd_loan_agreement.createDateTime
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setCreatedatetime(Date createdatetime) {
        this.createdatetime = createdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_loan_agreement.userID
     *
     * @return the value of rd_loan_agreement.userID
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getUserid() {
        return userid;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_loan_agreement.userID
     *
     * @param userid the value for rd_loan_agreement.userID
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_loan_agreement.debiterName
     *
     * @return the value of rd_loan_agreement.debiterName
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getDebitername() {
        return debitername;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_loan_agreement.debiterName
     *
     * @param debitername the value for rd_loan_agreement.debiterName
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setDebitername(String debitername) {
        this.debitername = debitername == null ? null : debitername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_loan_agreement.debiterIdentity
     *
     * @return the value of rd_loan_agreement.debiterIdentity
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getDebiteridentity() {
        return debiteridentity;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_loan_agreement.debiterIdentity
     *
     * @param debiteridentity the value for rd_loan_agreement.debiterIdentity
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setDebiteridentity(String debiteridentity) {
        this.debiteridentity = debiteridentity == null ? null : debiteridentity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_loan_agreement.debiterQualifierType
     *
     * @return the value of rd_loan_agreement.debiterQualifierType
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getDebiterqualifiertype() {
        return debiterqualifiertype;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_loan_agreement.debiterQualifierType
     *
     * @param debiterqualifiertype the value for rd_loan_agreement.debiterQualifierType
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setDebiterqualifiertype(String debiterqualifiertype) {
        this.debiterqualifiertype = debiterqualifiertype == null ? null : debiterqualifiertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_loan_agreement.debitPurpose
     *
     * @return the value of rd_loan_agreement.debitPurpose
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getDebitpurpose() {
        return debitpurpose;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_loan_agreement.debitPurpose
     *
     * @param debitpurpose the value for rd_loan_agreement.debitPurpose
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setDebitpurpose(String debitpurpose) {
        this.debitpurpose = debitpurpose == null ? null : debitpurpose.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_loan_agreement.paybackStartDate
     *
     * @return the value of rd_loan_agreement.paybackStartDate
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Date getPaybackstartdate() {
        return paybackstartdate;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_loan_agreement.paybackStartDate
     *
     * @param paybackstartdate the value for rd_loan_agreement.paybackStartDate
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setPaybackstartdate(Date paybackstartdate) {
        this.paybackstartdate = paybackstartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_loan_agreement.debitAmount
     *
     * @return the value of rd_loan_agreement.debitAmount
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Long getDebitamount() {
        return debitamount;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_loan_agreement.debitAmount
     *
     * @param debitamount the value for rd_loan_agreement.debitAmount
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setDebitamount(Long debitamount) {
        this.debitamount = debitamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_loan_agreement.debitDuration
     *
     * @return the value of rd_loan_agreement.debitDuration
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Integer getDebitduration() {
        return debitduration;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_loan_agreement.debitDuration
     *
     * @param debitduration the value for rd_loan_agreement.debitDuration
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setDebitduration(Integer debitduration) {
        this.debitduration = debitduration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_loan_agreement.productNum
     *
     * @return the value of rd_loan_agreement.productNum
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Integer getProductnum() {
        return productnum;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_loan_agreement.productNum
     *
     * @param productnum the value for rd_loan_agreement.productNum
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setProductnum(Integer productnum) {
        this.productnum = productnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_loan_agreement.deptMethod
     *
     * @return the value of rd_loan_agreement.deptMethod
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getDeptmethod() {
        return deptmethod;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_loan_agreement.deptMethod
     *
     * @param deptmethod the value for rd_loan_agreement.deptMethod
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setDeptmethod(String deptmethod) {
        this.deptmethod = deptmethod == null ? null : deptmethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_loan_agreement.finished
     *
     * @return the value of rd_loan_agreement.finished
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Integer getFinished() {
        return finished;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_loan_agreement.finished
     *
     * @param finished the value for rd_loan_agreement.finished
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setFinished(Integer finished) {
        this.finished = finished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_loan_agreement.restMoneyDays
     *
     * @return the value of rd_loan_agreement.restMoneyDays
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Long getRestmoneydays() {
        return restmoneydays;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_loan_agreement.restMoneyDays
     *
     * @param restmoneydays the value for rd_loan_agreement.restMoneyDays
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setRestmoneydays(Long restmoneydays) {
        this.restmoneydays = restmoneydays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_loan_agreement.totalMoneyDays
     *
     * @return the value of rd_loan_agreement.totalMoneyDays
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Long getTotalmoneydays() {
        return totalmoneydays;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_loan_agreement.totalMoneyDays
     *
     * @param totalmoneydays the value for rd_loan_agreement.totalMoneyDays
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setTotalmoneydays(Long totalmoneydays) {
        this.totalmoneydays = totalmoneydays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_loan_agreement.debiterQualifierTypeId
     *
     * @return the value of rd_loan_agreement.debiterQualifierTypeId
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getLoanNumber() {
        return loanNumber;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_loan_agreement.debiterQualifierTypeId
     *
     * @param debiterqualifiertypeid the value for rd_loan_agreement.debiterQualifierTypeId
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setLoanNumber(String loanNumber) {
        this.loanNumber = loanNumber == null ? null : loanNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_loan_agreement.debitPurposeId
     *
     * @return the value of rd_loan_agreement.debitPurposeId
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Long getRestDebitAmount() {
        return restDebitAmount;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_loan_agreement.debitPurposeId
     *
     * @param debitpurposeid the value for rd_loan_agreement.debitPurposeId
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setRestDebitAmount(Long restDebitAmount) {
        this.restDebitAmount = restDebitAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_loan_agreement.deptMethodId
     *
     * @return the value of rd_loan_agreement.deptMethodId
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Integer getRestDebitDuration() {
        return restDebitDuration;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_loan_agreement.deptMethodId
     *
     * @param deptmethodid the value for rd_loan_agreement.deptMethodId
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setRestDebitDuration(Integer restDebitDuration) {
        this.restDebitDuration = restDebitDuration;
    }
    
    public String getProjectSource() {
		return projectSource;
	}
	public void setProjectSource(String projectSource) {
		this.projectSource = projectSource != null ? projectSource.trim() : null;
	}
	
	public String getBriefContent() {
		return briefContent;
	}
	public void setBriefContent(String briefContent) {
		this.briefContent = briefContent;
	}
	
}