package com.expocms.server.db.model;

public class RdNo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_no.ids
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String ids;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_no.tableName
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String tablename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_no.currentNo
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String currentno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_no.type
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_no.ids
     *
     * @return the value of rd_no.ids
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getIds() {
        return ids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_no.ids
     *
     * @param ids the value for rd_no.ids
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setIds(String ids) {
        this.ids = ids == null ? null : ids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_no.tableName
     *
     * @return the value of rd_no.tableName
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getTablename() {
        return tablename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_no.tableName
     *
     * @param tablename the value for rd_no.tableName
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setTablename(String tablename) {
        this.tablename = tablename == null ? null : tablename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_no.currentNo
     *
     * @return the value of rd_no.currentNo
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getCurrentno() {
        return currentno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_no.currentNo
     *
     * @param currentno the value for rd_no.currentNo
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setCurrentno(String currentno) {
        this.currentno = currentno == null ? null : currentno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_no.type
     *
     * @return the value of rd_no.type
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_no.type
     *
     * @param type the value for rd_no.type
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}