package com.expocms.server.db.model;

public class RdOperator {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_operator.ids
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String ids;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_operator.version
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Long version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_operator.description
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_operator.name
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_operator.onemany
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String onemany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_operator.returnparamkeys
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String returnparamkeys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_operator.returnurl
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String returnurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_operator.rowfilter
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String rowfilter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_operator.url
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_operator.moduleids
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String moduleids;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_operator.splitpage
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String splitpage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_operator.formtoken
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String formtoken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_operator.ipblack
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String ipblack;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_operator.privilegess
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String privilegess;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_operator.ispv
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String ispv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_operator.pvtype
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String pvtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_operator.modulenames
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String modulenames;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_operator.ids
     *
     * @return the value of rd_operator.ids
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getIds() {
        return ids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_operator.ids
     *
     * @param ids the value for rd_operator.ids
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setIds(String ids) {
        this.ids = ids == null ? null : ids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_operator.version
     *
     * @return the value of rd_operator.version
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_operator.version
     *
     * @param version the value for rd_operator.version
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_operator.description
     *
     * @return the value of rd_operator.description
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_operator.description
     *
     * @param description the value for rd_operator.description
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_operator.name
     *
     * @return the value of rd_operator.name
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_operator.name
     *
     * @param name the value for rd_operator.name
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_operator.onemany
     *
     * @return the value of rd_operator.onemany
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getOnemany() {
        return onemany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_operator.onemany
     *
     * @param onemany the value for rd_operator.onemany
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setOnemany(String onemany) {
        this.onemany = onemany == null ? null : onemany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_operator.returnparamkeys
     *
     * @return the value of rd_operator.returnparamkeys
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getReturnparamkeys() {
        return returnparamkeys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_operator.returnparamkeys
     *
     * @param returnparamkeys the value for rd_operator.returnparamkeys
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setReturnparamkeys(String returnparamkeys) {
        this.returnparamkeys = returnparamkeys == null ? null : returnparamkeys.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_operator.returnurl
     *
     * @return the value of rd_operator.returnurl
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getReturnurl() {
        return returnurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_operator.returnurl
     *
     * @param returnurl the value for rd_operator.returnurl
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setReturnurl(String returnurl) {
        this.returnurl = returnurl == null ? null : returnurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_operator.rowfilter
     *
     * @return the value of rd_operator.rowfilter
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getRowfilter() {
        return rowfilter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_operator.rowfilter
     *
     * @param rowfilter the value for rd_operator.rowfilter
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setRowfilter(String rowfilter) {
        this.rowfilter = rowfilter == null ? null : rowfilter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_operator.url
     *
     * @return the value of rd_operator.url
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_operator.url
     *
     * @param url the value for rd_operator.url
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_operator.moduleids
     *
     * @return the value of rd_operator.moduleids
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getModuleids() {
        return moduleids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_operator.moduleids
     *
     * @param moduleids the value for rd_operator.moduleids
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setModuleids(String moduleids) {
        this.moduleids = moduleids == null ? null : moduleids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_operator.splitpage
     *
     * @return the value of rd_operator.splitpage
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getSplitpage() {
        return splitpage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_operator.splitpage
     *
     * @param splitpage the value for rd_operator.splitpage
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setSplitpage(String splitpage) {
        this.splitpage = splitpage == null ? null : splitpage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_operator.formtoken
     *
     * @return the value of rd_operator.formtoken
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getFormtoken() {
        return formtoken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_operator.formtoken
     *
     * @param formtoken the value for rd_operator.formtoken
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setFormtoken(String formtoken) {
        this.formtoken = formtoken == null ? null : formtoken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_operator.ipblack
     *
     * @return the value of rd_operator.ipblack
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getIpblack() {
        return ipblack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_operator.ipblack
     *
     * @param ipblack the value for rd_operator.ipblack
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setIpblack(String ipblack) {
        this.ipblack = ipblack == null ? null : ipblack.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_operator.privilegess
     *
     * @return the value of rd_operator.privilegess
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getPrivilegess() {
        return privilegess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_operator.privilegess
     *
     * @param privilegess the value for rd_operator.privilegess
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setPrivilegess(String privilegess) {
        this.privilegess = privilegess == null ? null : privilegess.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_operator.ispv
     *
     * @return the value of rd_operator.ispv
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getIspv() {
        return ispv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_operator.ispv
     *
     * @param ispv the value for rd_operator.ispv
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setIspv(String ispv) {
        this.ispv = ispv == null ? null : ispv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_operator.pvtype
     *
     * @return the value of rd_operator.pvtype
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getPvtype() {
        return pvtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_operator.pvtype
     *
     * @param pvtype the value for rd_operator.pvtype
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setPvtype(String pvtype) {
        this.pvtype = pvtype == null ? null : pvtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_operator.modulenames
     *
     * @return the value of rd_operator.modulenames
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getModulenames() {
        return modulenames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_operator.modulenames
     *
     * @param modulenames the value for rd_operator.modulenames
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setModulenames(String modulenames) {
        this.modulenames = modulenames == null ? null : modulenames.trim();
    }
}