package com.expocms.server.db.model;

public class RdOrderKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_order.id
     *
     * @mbggenerated Tue Aug 25 09:47:54 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_order.product_id
     *
     * @mbggenerated Tue Aug 25 09:47:54 CST 2015
     */
    private Long productId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_order.id
     *
     * @return the value of rd_order.id
     *
     * @mbggenerated Tue Aug 25 09:47:54 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_order.id
     *
     * @param id the value for rd_order.id
     *
     * @mbggenerated Tue Aug 25 09:47:54 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_order.product_id
     *
     * @return the value of rd_order.product_id
     *
     * @mbggenerated Tue Aug 25 09:47:54 CST 2015
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_order.product_id
     *
     * @param productId the value for rd_order.product_id
     *
     * @mbggenerated Tue Aug 25 09:47:54 CST 2015
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }
}