package com.expocms.server.db.model;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

public class RdOrder {
	
	/**
	 * order status ...
	 */
	public static final int ORDER_STATUS_SEALED   = 1;  // 封闭期
	public static final int ORDER_STATUS_REPAYING = 2;  // 赎回中
	public static final int ORDER_STATUS_REPAIED  = 3;  // 已赎回
	public static final int ORDER_STATUS_PAYING   = 4;  // 支付中
	
	public static final String ORDER_STR_STATUS_SEALED   = "封闭期";
	public static final String ORDER_STR_STATUS_REPAYING = "赎回中";
	public static final String ORDER_STR_STATUS_REPAIED  = "已赎回";
	public static final String ORDER_STR_STATUS_PAYING   = "支付中";
	
	/**
	 * order type ...
	 */
	public static final int ORDER_TYPE_PAYING     = 1;  // 收（购买订单）
	public static final int ORDER_TYPE_REPAYING   = 2;  // 付（赎回订单）
	
	/**
	 * repay status ...
	 */
	public static final int ORDER_REPAY_STATUS_BEFORE_REPAY  = 0;  // 赎回前
	public static final int ORDER_REPAY_STATUS_REPAYING      = 1;  // 赎回中
	public static final int ORDER_REPAY_STATUS_REPAY_SUCCESS = 2;  // 赎回成功
	public static final int ORDER_REPAY_STATUS_REPAY_FAILED  = 3;  // 赎回失败
	
	/**
	 * map of orfer status ...
	 */
	@SuppressWarnings("serial")
	public final static Map<Integer, String> ORDER_STATUS_MAP = new HashMap<Integer, String>() {{
		put(new Integer(ORDER_STATUS_SEALED), ORDER_STR_STATUS_SEALED);
		put(new Integer(ORDER_STATUS_REPAYING), ORDER_STR_STATUS_REPAYING);
		put(new Integer(ORDER_STATUS_REPAIED), ORDER_STR_STATUS_REPAIED);
		put(new Integer(ORDER_STATUS_PAYING), ORDER_STR_STATUS_PAYING);
	}};
	
	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_order.ids
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String ids;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_order.no
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String no;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_order.sex
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String sex;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_order.appUserName
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String appusername;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_order.appUserID
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String appuserid;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_order.appUserIdentity
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String appuseridentity;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_order.cardNO
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String cardno;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_order.interestStartDate
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Date intereststartdate;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_order.interestEndDate
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Date interestenddate;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_order.age
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Integer age;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_order.productName
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String productname;
    private String productseries;
    private String appUserPhone;
    private String contractContent;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_order.productIds
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String productids;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_order.assignmentId
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String assignmentid;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_order.duration
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Integer duration;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_order.amount
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Long amount;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_order.actualAmount
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Long actualamount;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_order.interest
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Float interest;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_order.orderType
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String ordertype;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_order.orderCreateTime
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Date ordercreatetime;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_order.orderTransferTime
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Date ordertransfertime;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_order.payAmount
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Long payamount;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_order.giftAmount
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Long giftamount;
    private String giftCode;
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_order.isPaid
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Integer ispaid;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_order.isCheckOk
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Integer ischeckok;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_order.repaidAmount
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Long repaidamount;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_order.predictRepayDateTime
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Date predictrepaydatetime;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_order.endDate
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Date enddate;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_order.status
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Integer status;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_order.repayStatus
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Integer repaystatus;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_order.repayErrorMsg
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String repayerrormsg;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_order.isDeleted
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Integer isdeleted;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_order.bankName
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String bankname;
    private String bankCardNo;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_order.productNo
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String productno;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_order.assignNo
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String assignno;
    private Long currentPoperty;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_order.ids
     *
     * @return the value of rd_order.ids
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getIds() {
        return ids;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_order.ids
     *
     * @param ids the value for rd_order.ids
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setIds(String ids) {
        this.ids = ids == null ? null : ids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_order.no
     *
     * @return the value of rd_order.no
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getNo() {
        return no;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_order.no
     *
     * @param no the value for rd_order.no
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setNo(String no) {
        this.no = no == null ? null : no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_order.sex
     *
     * @return the value of rd_order.sex
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getSex() {
        return sex;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_order.sex
     *
     * @param sex the value for rd_order.sex
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_order.appUserName
     *
     * @return the value of rd_order.appUserName
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getAppusername() {
        return appusername;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_order.appUserName
     *
     * @param appusername the value for rd_order.appUserName
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setAppusername(String appusername) {
        this.appusername = appusername == null ? null : appusername.trim();
    }

    public String getAppUserPhone() {
        return appUserPhone;
    }
    public void setAppUserPhone(String appUserPhone) {
        this.appUserPhone = appUserPhone;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_order.appUserID
     *
     * @return the value of rd_order.appUserID
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getAppuserid() {
        return appuserid;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_order.appUserID
     *
     * @param appuserid the value for rd_order.appUserID
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setAppuserid(String appuserid) {
        this.appuserid = appuserid == null ? null : appuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_order.appUserIdentity
     *
     * @return the value of rd_order.appUserIdentity
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getAppuseridentity() {
        return appuseridentity;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_order.appUserIdentity
     *
     * @param appuseridentity the value for rd_order.appUserIdentity
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setAppuseridentity(String appuseridentity) {
        this.appuseridentity = appuseridentity == null ? null : appuseridentity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_order.cardNO
     *
     * @return the value of rd_order.cardNO
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getCardno() {
        return cardno;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_order.cardNO
     *
     * @param cardno the value for rd_order.cardNO
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setCardno(String cardno) {
        this.cardno = cardno == null ? null : cardno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_order.interestStartDate
     *
     * @return the value of rd_order.interestStartDate
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Date getIntereststartdate() {
        return intereststartdate;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_order.interestStartDate
     *
     * @param intereststartdate the value for rd_order.interestStartDate
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setIntereststartdate(Date intereststartdate) {
        this.intereststartdate = intereststartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_order.interestEndDate
     *
     * @return the value of rd_order.interestEndDate
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Date getInterestenddate() {
        return interestenddate;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_order.interestEndDate
     *
     * @param interestenddate the value for rd_order.interestEndDate
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setInterestenddate(Date interestenddate) {
        this.interestenddate = interestenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_order.age
     *
     * @return the value of rd_order.age
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Integer getAge() {
        return age;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_order.age
     *
     * @param age the value for rd_order.age
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_order.productName
     *
     * @return the value of rd_order.productName
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getProductname() {
        return productname;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_order.productName
     *
     * @param productname the value for rd_order.productName
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setProductname(String productname) {
        this.productname = productname == null ? null : productname.trim();
    }
    
    public String getProductseries() {
    	return productseries;
    }
    public void setProductseries(String productseries) {
        this.productseries = productseries == null ? null : productseries.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_order.productIds
     *
     * @return the value of rd_order.productIds
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getProductids() {
        return productids;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_order.productIds
     *
     * @param productids the value for rd_order.productIds
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setProductids(String productids) {
        this.productids = productids == null ? null : productids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_order.assignmentId
     *
     * @return the value of rd_order.assignmentId
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getAssignmentid() {
        return assignmentid;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_order.assignmentId
     *
     * @param assignmentid the value for rd_order.assignmentId
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setAssignmentid(String assignmentid) {
        this.assignmentid = assignmentid == null ? null : assignmentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_order.duration
     *
     * @return the value of rd_order.duration
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Integer getDuration() {
        return duration;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_order.duration
     *
     * @param duration the value for rd_order.duration
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_order.amount
     *
     * @return the value of rd_order.amount
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Long getAmount() {
        return amount;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_order.amount
     *
     * @param amount the value for rd_order.amount
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_order.actualAmount
     *
     * @return the value of rd_order.actualAmount
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Long getActualamount() {
        return actualamount;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_order.actualAmount
     *
     * @param actualamount the value for rd_order.actualAmount
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setActualamount(Long actualamount) {
        this.actualamount = actualamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_order.interest
     *
     * @return the value of rd_order.interest
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Float getInterest() {
        return interest;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_order.interest
     *
     * @param interest the value for rd_order.interest
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setInterest(Float interest) {
        this.interest = interest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_order.orderType
     *
     * @return the value of rd_order.orderType
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getOrdertype() {
        return ordertype;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_order.orderType
     *
     * @param ordertype the value for rd_order.orderType
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setOrdertype(String ordertype) {
        this.ordertype = ordertype == null ? null : ordertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_order.orderCreateTime
     *
     * @return the value of rd_order.orderCreateTime
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Date getOrdercreatetime() {
        return ordercreatetime;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_order.orderCreateTime
     *
     * @param ordercreatetime the value for rd_order.orderCreateTime
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setOrdercreatetime(Date ordercreatetime) {
        this.ordercreatetime = ordercreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_order.orderTransferTime
     *
     * @return the value of rd_order.orderTransferTime
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Date getOrdertransfertime() {
        return ordertransfertime;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_order.orderTransferTime
     *
     * @param ordertransfertime the value for rd_order.orderTransferTime
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setOrdertransfertime(Date ordertransfertime) {
        this.ordertransfertime = ordertransfertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_order.payAmount
     *
     * @return the value of rd_order.payAmount
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Long getPayamount() {
        return payamount;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_order.payAmount
     *
     * @param payamount the value for rd_order.payAmount
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setPayamount(Long payamount) {
        this.payamount = payamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_order.giftAmount
     *
     * @return the value of rd_order.giftAmount
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Long getGiftamount() {
        return giftamount;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_order.giftAmount
     *
     * @param giftamount the value for rd_order.giftAmount
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setGiftamount(Long giftamount) {
        this.giftamount = giftamount;
    }
    
    public String getGiftCode() {
		return giftCode;
	}
	public void setGiftCode(String giftCode) {
		this.giftCode = giftCode;
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_order.isPaid
     *
     * @return the value of rd_order.isPaid
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Integer getIspaid() {
        return ispaid;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_order.isPaid
     *
     * @param ispaid the value for rd_order.isPaid
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setIspaid(Integer ispaid) {
        this.ispaid = ispaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_order.isCheckOk
     *
     * @return the value of rd_order.isCheckOk
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Integer getIscheckok() {
        return ischeckok;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_order.isCheckOk
     *
     * @param ischeckok the value for rd_order.isCheckOk
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setIscheckok(Integer ischeckok) {
        this.ischeckok = ischeckok;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_order.repaidAmount
     *
     * @return the value of rd_order.repaidAmount
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Long getRepaidamount() {
        return repaidamount;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_order.repaidAmount
     *
     * @param repaidamount the value for rd_order.repaidAmount
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setRepaidamount(Long repaidamount) {
        this.repaidamount = repaidamount;
    }
    
    public Long getCurrentPoperty() {
    	return currentPoperty;
    }
    public void setCurrentPoperty(Long currentPoperty) {
    	this.currentPoperty = currentPoperty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_order.predictRepayDateTime
     *
     * @return the value of rd_order.predictRepayDateTime
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Date getPredictrepaydatetime() {
        return predictrepaydatetime;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_order.predictRepayDateTime
     *
     * @param predictrepaydatetime the value for rd_order.predictRepayDateTime
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setPredictrepaydatetime(Date predictrepaydatetime) {
        this.predictrepaydatetime = predictrepaydatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_order.endDate
     *
     * @return the value of rd_order.endDate
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Date getEnddate() {
        return enddate;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_order.endDate
     *
     * @param enddate the value for rd_order.endDate
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_order.status
     *
     * @return the value of rd_order.status
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Integer getStatus() {
        return status;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_order.status
     *
     * @param status the value for rd_order.status
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_order.repayStatus
     *
     * @return the value of rd_order.repayStatus
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Integer getRepaystatus() {
        return repaystatus;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_order.repayStatus
     *
     * @param repaystatus the value for rd_order.repayStatus
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setRepaystatus(Integer repaystatus) {
        this.repaystatus = repaystatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_order.repayErrorMsg
     *
     * @return the value of rd_order.repayErrorMsg
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getRepayerrormsg() {
        return repayerrormsg;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_order.repayErrorMsg
     *
     * @param repayerrormsg the value for rd_order.repayErrorMsg
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setRepayerrormsg(String repayerrormsg) {
        this.repayerrormsg = repayerrormsg == null ? null : repayerrormsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_order.isDeleted
     *
     * @return the value of rd_order.isDeleted
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Integer getIsdeleted() {
        return isdeleted;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_order.isDeleted
     *
     * @param isdeleted the value for rd_order.isDeleted
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setIsdeleted(Integer isdeleted) {
        this.isdeleted = isdeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_order.bankName
     *
     * @return the value of rd_order.bankName
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getBankname() {
        return bankname;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_order.bankName
     *
     * @param bankname the value for rd_order.bankName
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setBankname(String bankname) {
        this.bankname = bankname == null ? null : bankname.trim();
    }
    
    public String getBankCardNo() {
    	return bankCardNo;
    }
    public void setBankCardNo(String bankCardNo) {
    	this.bankCardNo = bankCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_order.productNo
     *
     * @return the value of rd_order.productNo
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getProductno() {
        return productno;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_order.productNo
     *
     * @param productno the value for rd_order.productNo
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setProductno(String productno) {
        this.productno = productno == null ? null : productno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_order.assignNo
     *
     * @return the value of rd_order.assignNo
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getAssignno() {
        return assignno;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_order.assignNo
     *
     * @param assignno the value for rd_order.assignNo
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setAssignno(String assignno) {
        this.assignno = assignno == null ? null : assignno.trim();
    }
    
    public String getContractContent() {
    	return contractContent;
    }
    public void setContractContent(String contractContent) {
    	this.contractContent = contractContent;
    }
    
}