package com.expocms.server.db.model;

import java.util.Date;

public class RdPaymentRefound {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_payment_refound.ids
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String ids;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_payment_refound.province_city
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String provinceCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_payment_refound.bankName
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String bankname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_payment_refound.kaihuhang
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String kaihuhang;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_payment_refound.creditName
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String creditname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_payment_refound.creditContact
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String creditcontact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_payment_refound.bankCardNumber
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String bankcardnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_payment_refound.currencyCode
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Integer currencycode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_payment_refound.amount
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Long amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_payment_refound.description
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_payment_refound.correctName
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String correctname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_payment_refound.tempAccount
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String tempaccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_payment_refound.orderId
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_payment_refound.dealId
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String dealid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_payment_refound.dealCharge
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Long dealcharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_payment_refound.debitCharge
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Long debitcharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_payment_refound.creditCharge
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Long creditcharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_payment_refound.resultFlag
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String resultflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_payment_refound.failureCause
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String failurecause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_payment_refound.mac
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String mac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_payment_refound.createTime
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_payment_refound.ids
     *
     * @return the value of rd_payment_refound.ids
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getIds() {
        return ids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_payment_refound.ids
     *
     * @param ids the value for rd_payment_refound.ids
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setIds(String ids) {
        this.ids = ids == null ? null : ids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_payment_refound.province_city
     *
     * @return the value of rd_payment_refound.province_city
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getProvinceCity() {
        return provinceCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_payment_refound.province_city
     *
     * @param provinceCity the value for rd_payment_refound.province_city
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setProvinceCity(String provinceCity) {
        this.provinceCity = provinceCity == null ? null : provinceCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_payment_refound.bankName
     *
     * @return the value of rd_payment_refound.bankName
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getBankname() {
        return bankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_payment_refound.bankName
     *
     * @param bankname the value for rd_payment_refound.bankName
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setBankname(String bankname) {
        this.bankname = bankname == null ? null : bankname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_payment_refound.kaihuhang
     *
     * @return the value of rd_payment_refound.kaihuhang
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getKaihuhang() {
        return kaihuhang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_payment_refound.kaihuhang
     *
     * @param kaihuhang the value for rd_payment_refound.kaihuhang
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setKaihuhang(String kaihuhang) {
        this.kaihuhang = kaihuhang == null ? null : kaihuhang.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_payment_refound.creditName
     *
     * @return the value of rd_payment_refound.creditName
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getCreditname() {
        return creditname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_payment_refound.creditName
     *
     * @param creditname the value for rd_payment_refound.creditName
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setCreditname(String creditname) {
        this.creditname = creditname == null ? null : creditname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_payment_refound.creditContact
     *
     * @return the value of rd_payment_refound.creditContact
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getCreditcontact() {
        return creditcontact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_payment_refound.creditContact
     *
     * @param creditcontact the value for rd_payment_refound.creditContact
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setCreditcontact(String creditcontact) {
        this.creditcontact = creditcontact == null ? null : creditcontact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_payment_refound.bankCardNumber
     *
     * @return the value of rd_payment_refound.bankCardNumber
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getBankcardnumber() {
        return bankcardnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_payment_refound.bankCardNumber
     *
     * @param bankcardnumber the value for rd_payment_refound.bankCardNumber
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setBankcardnumber(String bankcardnumber) {
        this.bankcardnumber = bankcardnumber == null ? null : bankcardnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_payment_refound.currencyCode
     *
     * @return the value of rd_payment_refound.currencyCode
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Integer getCurrencycode() {
        return currencycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_payment_refound.currencyCode
     *
     * @param currencycode the value for rd_payment_refound.currencyCode
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setCurrencycode(Integer currencycode) {
        this.currencycode = currencycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_payment_refound.amount
     *
     * @return the value of rd_payment_refound.amount
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_payment_refound.amount
     *
     * @param amount the value for rd_payment_refound.amount
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_payment_refound.description
     *
     * @return the value of rd_payment_refound.description
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_payment_refound.description
     *
     * @param description the value for rd_payment_refound.description
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_payment_refound.correctName
     *
     * @return the value of rd_payment_refound.correctName
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getCorrectname() {
        return correctname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_payment_refound.correctName
     *
     * @param correctname the value for rd_payment_refound.correctName
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setCorrectname(String correctname) {
        this.correctname = correctname == null ? null : correctname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_payment_refound.tempAccount
     *
     * @return the value of rd_payment_refound.tempAccount
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getTempaccount() {
        return tempaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_payment_refound.tempAccount
     *
     * @param tempaccount the value for rd_payment_refound.tempAccount
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setTempaccount(String tempaccount) {
        this.tempaccount = tempaccount == null ? null : tempaccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_payment_refound.orderId
     *
     * @return the value of rd_payment_refound.orderId
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_payment_refound.orderId
     *
     * @param orderid the value for rd_payment_refound.orderId
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setOrderid(String orderid) {
        this.orderid = orderid == null ? null : orderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_payment_refound.dealId
     *
     * @return the value of rd_payment_refound.dealId
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getDealid() {
        return dealid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_payment_refound.dealId
     *
     * @param dealid the value for rd_payment_refound.dealId
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setDealid(String dealid) {
        this.dealid = dealid == null ? null : dealid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_payment_refound.dealCharge
     *
     * @return the value of rd_payment_refound.dealCharge
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Long getDealcharge() {
        return dealcharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_payment_refound.dealCharge
     *
     * @param dealcharge the value for rd_payment_refound.dealCharge
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setDealcharge(Long dealcharge) {
        this.dealcharge = dealcharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_payment_refound.debitCharge
     *
     * @return the value of rd_payment_refound.debitCharge
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Long getDebitcharge() {
        return debitcharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_payment_refound.debitCharge
     *
     * @param debitcharge the value for rd_payment_refound.debitCharge
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setDebitcharge(Long debitcharge) {
        this.debitcharge = debitcharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_payment_refound.creditCharge
     *
     * @return the value of rd_payment_refound.creditCharge
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Long getCreditcharge() {
        return creditcharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_payment_refound.creditCharge
     *
     * @param creditcharge the value for rd_payment_refound.creditCharge
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setCreditcharge(Long creditcharge) {
        this.creditcharge = creditcharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_payment_refound.resultFlag
     *
     * @return the value of rd_payment_refound.resultFlag
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getResultflag() {
        return resultflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_payment_refound.resultFlag
     *
     * @param resultflag the value for rd_payment_refound.resultFlag
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setResultflag(String resultflag) {
        this.resultflag = resultflag == null ? null : resultflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_payment_refound.failureCause
     *
     * @return the value of rd_payment_refound.failureCause
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getFailurecause() {
        return failurecause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_payment_refound.failureCause
     *
     * @param failurecause the value for rd_payment_refound.failureCause
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setFailurecause(String failurecause) {
        this.failurecause = failurecause == null ? null : failurecause.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_payment_refound.mac
     *
     * @return the value of rd_payment_refound.mac
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getMac() {
        return mac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_payment_refound.mac
     *
     * @param mac the value for rd_payment_refound.mac
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setMac(String mac) {
        this.mac = mac == null ? null : mac.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_payment_refound.createTime
     *
     * @return the value of rd_payment_refound.createTime
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_payment_refound.createTime
     *
     * @param createtime the value for rd_payment_refound.createTime
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}