package com.expocms.server.db.model;

import java.io.Serializable;
import java.util.Date;

public class RdProduct implements Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = -2561095398822229884L;
	
	
	/**
	 * product type ...
	 */
	public static final int PRODUCT_TYPE_NEW_HAND    = 1;  // 新手专享
	public static final int PRODUCT_TYPE_RECOMMENDED = 2;  // 精品推荐
	public static final int PRODUCT_TYPE_HOT_SOLD    = 3;  // 热销产品
	public static final int PRODUCT_TYPE_FIRE_SOLD   = 4;  // 火爆产品
	
	/**
	 * status ...
	 */
	public static final int PRODUCT_STATUS_PENDING_APPROVAL   = 1; // 待审核
	public static final int PRODUCT_STATUS_PENDING_ONLINE     = 2; // 待上架
	public static final int PRODUCT_STATUS_AUDIT_DENIED       = 3; // 审核不通过
	public static final int PRODUCT_STATUS_IN_SAIL            = 4; // 在售
	public static final int PRODUCT_STATUS_SOLD_OUT           = 5; // 已售罄
	public static final int PRODUCT_STATUS_FULL_SCALE         = 6; // 已满标
	public static final int PRODUCT_STATUS_REPAIED            = 7; // 已还款
	public static final int PRODUCT_STATUS_DELETED            = 8; // 已删除
	
	public static final String PRODUCT_STATUS_STR_PENDING_APPROVAL   = ""; // 待审核
	public static final String PRODUCT_STATUS_STR_PENDING_ONLINE     = ""; // 待上架
	public static final String PRODUCT_STATUS_STR_AUDIT_DENIED       = ""; // 审核不通过
	public static final String PRODUCT_STATUS_STR_IN_SAIL            = ""; // 在售
	public static final String PRODUCT_STATUS_STR_SOLD_OUT           = "alreadySellOut";   // 已售罄
	public static final String PRODUCT_STATUS_STR_FULL_SCALE         = ""; // 已满标
	public static final String PRODUCT_STATUS_STR_REPAIED            = "alreadyRepayment"; // 已还款
	public static final String PRODUCT_STATUS_STR_DELETED            = ""; // 已删除
	
	/**
	 * offline reason ...
	 */
	public static final int PRODUCT_OFFLINE_FULL_SCALE         = 1;
	public static final int PRODUCT_OFFLINE_MANUAL             = 2;
	public static final int PRODUCT_OFFLINE_AUTO               = 3;
	
	public static final String PRODUCT_OFFLINE_STR_FULL_SCALE  = "满标下架";
	public static final String PRODUCT_OFFLINE_STR_MANUAL      = "手动下架";
	public static final String PRODUCT_OFFLINE_STR_AUTO        = "自动下架";
	
	
	/**
	 * combine name and series ...
	 * @param name
	 * @param series
	 * @return
	 */
	public static String getFullProudctName(final String name, final String series) {
		if(name == null || name.equals(""))
			return "";
		
		if(series != null && series.equals("") == false)
			return name + "第" + series + "期";
		
		return name;
	}
	

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_product.ids
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String ids;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_product.no
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_product.assignmentNo
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String assignmentno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_product.productName
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String productname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_product.series
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String series;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_product.productAmount
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Long productamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_product.investigateDuration
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Integer investigateduration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_product.status
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_product.uploadDateTime
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Date uploaddatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_product.productType
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String producttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_product.interest
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Float interest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_product.minInvestigateAmount
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Long mininvestigateamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_product.maxInvestigateAmount
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Long maxinvestigateamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_product.finishDateTime
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Date finishdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_product.modifyDateTime
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Date modifydatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_product.submitUserId
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String submituserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_product.submitUser
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String submituser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_product.verifyUserId
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String verifyuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_product.verifyUser
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String verifyuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_product.buyerNum
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Long buyernum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_product.soldAmount
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Long soldamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_product.createDateTime
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Date createdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_product.endInterestDate
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Date endinterestdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_product.startInterestDate
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Date startinterestdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_product.repaidAmount
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Long repaidamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_product.finishVerifyUserId
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String finishverifyuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_product.finishVerifytUser
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String finishverifytuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_product.isPerfered
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Integer isperfered;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_product.successRecords
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Integer successrecords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_product.successAmount
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Long successamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_product.failRecords
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Integer failrecords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_product.failAmount
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Long failamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_product.userID
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_product.totalMoneyDays
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Long totalmoneydays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_product.assignId
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String assignid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_product.startDate
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Date startdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_product.endDate
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Date enddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_product.unPassReason
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String unpassreason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_product.isAllCheckOK
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Integer isallcheckok;
    
    private Integer offlineReason;
    
    private Date unsaleDateTime;


	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_product.ids
     *
     * @return the value of rd_product.ids
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getIds() {
        return ids;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_product.ids
     *
     * @param ids the value for rd_product.ids
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setIds(String ids) {
        this.ids = ids == null ? null : ids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_product.no
     *
     * @return the value of rd_product.no
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getNo() {
        return no;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_product.no
     *
     * @param no the value for rd_product.no
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setNo(String no) {
        this.no = no == null ? null : no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_product.assignmentNo
     *
     * @return the value of rd_product.assignmentNo
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getAssignmentno() {
        return assignmentno;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_product.assignmentNo
     *
     * @param assignmentno the value for rd_product.assignmentNo
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setAssignmentno(String assignmentno) {
        this.assignmentno = assignmentno == null ? null : assignmentno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_product.productName
     *
     * @return the value of rd_product.productName
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getProductname() {
        return productname;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_product.productName
     *
     * @param productname the value for rd_product.productName
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setProductname(String productname) {
        this.productname = productname == null ? null : productname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_product.series
     *
     * @return the value of rd_product.series
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getSeries() {
        return series;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_product.series
     *
     * @param series the value for rd_product.series
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setSeries(String series) {
        this.series = series == null ? null : series.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_product.productAmount
     *
     * @return the value of rd_product.productAmount
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Long getProductamount() {
        return productamount;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_product.productAmount
     *
     * @param productamount the value for rd_product.productAmount
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setProductamount(Long productamount) {
        this.productamount = productamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_product.investigateDuration
     *
     * @return the value of rd_product.investigateDuration
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Integer getInvestigateduration() {
        return investigateduration;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_product.investigateDuration
     *
     * @param investigateduration the value for rd_product.investigateDuration
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setInvestigateduration(Integer investigateduration) {
        this.investigateduration = investigateduration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_product.status
     *
     * @return the value of rd_product.status
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Integer getStatus() {
        return status;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_product.status
     *
     * @param status the value for rd_product.status
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_product.uploadDateTime
     *
     * @return the value of rd_product.uploadDateTime
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Date getUploaddatetime() {
        return uploaddatetime;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_product.uploadDateTime
     *
     * @param uploaddatetime the value for rd_product.uploadDateTime
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setUploaddatetime(Date uploaddatetime) {
        this.uploaddatetime = uploaddatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_product.productType
     *
     * @return the value of rd_product.productType
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getProducttype() {
        return producttype;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_product.productType
     *
     * @param producttype the value for rd_product.productType
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setProducttype(String producttype) {
        this.producttype = producttype == null ? null : producttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_product.interest
     *
     * @return the value of rd_product.interest
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Float getInterest() {
        return interest;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_product.interest
     *
     * @param interest the value for rd_product.interest
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setInterest(Float interest) {
        this.interest = interest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_product.minInvestigateAmount
     *
     * @return the value of rd_product.minInvestigateAmount
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Long getMininvestigateamount() {
        return mininvestigateamount;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_product.minInvestigateAmount
     *
     * @param mininvestigateamount the value for rd_product.minInvestigateAmount
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setMininvestigateamount(Long mininvestigateamount) {
        this.mininvestigateamount = mininvestigateamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_product.maxInvestigateAmount
     *
     * @return the value of rd_product.maxInvestigateAmount
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Long getMaxinvestigateamount() {
        return maxinvestigateamount;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_product.maxInvestigateAmount
     *
     * @param maxinvestigateamount the value for rd_product.maxInvestigateAmount
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setMaxinvestigateamount(Long maxinvestigateamount) {
        this.maxinvestigateamount = maxinvestigateamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_product.finishDateTime
     *
     * @return the value of rd_product.finishDateTime
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Date getFinishdatetime() {
        return finishdatetime;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_product.finishDateTime
     *
     * @param finishdatetime the value for rd_product.finishDateTime
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setFinishdatetime(Date finishdatetime) {
        this.finishdatetime = finishdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_product.modifyDateTime
     *
     * @return the value of rd_product.modifyDateTime
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Date getModifydatetime() {
        return modifydatetime;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_product.modifyDateTime
     *
     * @param modifydatetime the value for rd_product.modifyDateTime
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setModifydatetime(Date modifydatetime) {
        this.modifydatetime = modifydatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_product.submitUserId
     *
     * @return the value of rd_product.submitUserId
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getSubmituserid() {
        return submituserid;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_product.submitUserId
     *
     * @param submituserid the value for rd_product.submitUserId
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setSubmituserid(String submituserid) {
        this.submituserid = submituserid == null ? null : submituserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_product.submitUser
     *
     * @return the value of rd_product.submitUser
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getSubmituser() {
        return submituser;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_product.submitUser
     *
     * @param submituser the value for rd_product.submitUser
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setSubmituser(String submituser) {
        this.submituser = submituser == null ? null : submituser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_product.verifyUserId
     *
     * @return the value of rd_product.verifyUserId
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getVerifyuserid() {
        return verifyuserid;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_product.verifyUserId
     *
     * @param verifyuserid the value for rd_product.verifyUserId
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setVerifyuserid(String verifyuserid) {
        this.verifyuserid = verifyuserid == null ? null : verifyuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_product.verifyUser
     *
     * @return the value of rd_product.verifyUser
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getVerifyuser() {
        return verifyuser;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_product.verifyUser
     *
     * @param verifyuser the value for rd_product.verifyUser
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setVerifyuser(String verifyuser) {
        this.verifyuser = verifyuser == null ? null : verifyuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_product.buyerNum
     *
     * @return the value of rd_product.buyerNum
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Long getBuyernum() {
        return buyernum;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_product.buyerNum
     *
     * @param buyernum the value for rd_product.buyerNum
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setBuyernum(Long buyernum) {
        this.buyernum = buyernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_product.soldAmount
     *
     * @return the value of rd_product.soldAmount
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Long getSoldamount() {
        return soldamount;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_product.soldAmount
     *
     * @param soldamount the value for rd_product.soldAmount
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setSoldamount(Long soldamount) {
        this.soldamount = soldamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_product.createDateTime
     *
     * @return the value of rd_product.createDateTime
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Date getCreatedatetime() {
        return createdatetime;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_product.createDateTime
     *
     * @param createdatetime the value for rd_product.createDateTime
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setCreatedatetime(Date createdatetime) {
        this.createdatetime = createdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_product.endInterestDate
     *
     * @return the value of rd_product.endInterestDate
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Date getEndinterestdate() {
        return endinterestdate;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_product.endInterestDate
     *
     * @param endinterestdate the value for rd_product.endInterestDate
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setEndinterestdate(Date endinterestdate) {
        this.endinterestdate = endinterestdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_product.startInterestDate
     *
     * @return the value of rd_product.startInterestDate
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Date getStartinterestdate() {
        return startinterestdate;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_product.startInterestDate
     *
     * @param startinterestdate the value for rd_product.startInterestDate
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setStartinterestdate(Date startinterestdate) {
        this.startinterestdate = startinterestdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_product.repaidAmount
     *
     * @return the value of rd_product.repaidAmount
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Long getRepaidamount() {
        return repaidamount;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_product.repaidAmount
     *
     * @param repaidamount the value for rd_product.repaidAmount
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setRepaidamount(Long repaidamount) {
        this.repaidamount = repaidamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_product.finishVerifyUserId
     *
     * @return the value of rd_product.finishVerifyUserId
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getFinishverifyuserid() {
        return finishverifyuserid;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_product.finishVerifyUserId
     *
     * @param finishverifyuserid the value for rd_product.finishVerifyUserId
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setFinishverifyuserid(String finishverifyuserid) {
        this.finishverifyuserid = finishverifyuserid == null ? null : finishverifyuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_product.finishVerifytUser
     *
     * @return the value of rd_product.finishVerifytUser
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getFinishverifytuser() {
        return finishverifytuser;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_product.finishVerifytUser
     *
     * @param finishverifytuser the value for rd_product.finishVerifytUser
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setFinishverifytuser(String finishverifytuser) {
        this.finishverifytuser = finishverifytuser == null ? null : finishverifytuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_product.isPerfered
     *
     * @return the value of rd_product.isPerfered
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Integer getIsperfered() {
        return isperfered;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_product.isPerfered
     *
     * @param isperfered the value for rd_product.isPerfered
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setIsperfered(Integer isperfered) {
        this.isperfered = isperfered;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_product.successRecords
     *
     * @return the value of rd_product.successRecords
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Integer getSuccessrecords() {
        return successrecords;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_product.successRecords
     *
     * @param successrecords the value for rd_product.successRecords
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setSuccessrecords(Integer successrecords) {
        this.successrecords = successrecords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_product.successAmount
     *
     * @return the value of rd_product.successAmount
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Long getSuccessamount() {
        return successamount;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_product.successAmount
     *
     * @param successamount the value for rd_product.successAmount
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setSuccessamount(Long successamount) {
        this.successamount = successamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_product.failRecords
     *
     * @return the value of rd_product.failRecords
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Integer getFailrecords() {
        return failrecords;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_product.failRecords
     *
     * @param failrecords the value for rd_product.failRecords
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setFailrecords(Integer failrecords) {
        this.failrecords = failrecords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_product.failAmount
     *
     * @return the value of rd_product.failAmount
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Long getFailamount() {
        return failamount;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_product.failAmount
     *
     * @param failamount the value for rd_product.failAmount
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setFailamount(Long failamount) {
        this.failamount = failamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_product.userID
     *
     * @return the value of rd_product.userID
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getUserid() {
        return userid;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_product.userID
     *
     * @param userid the value for rd_product.userID
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_product.totalMoneyDays
     *
     * @return the value of rd_product.totalMoneyDays
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Long getTotalmoneydays() {
        return totalmoneydays;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_product.totalMoneyDays
     *
     * @param totalmoneydays the value for rd_product.totalMoneyDays
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setTotalmoneydays(Long totalmoneydays) {
        this.totalmoneydays = totalmoneydays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_product.assignId
     *
     * @return the value of rd_product.assignId
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getAssignid() {
        return assignid;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_product.assignId
     *
     * @param assignid the value for rd_product.assignId
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setAssignid(String assignid) {
        this.assignid = assignid == null ? null : assignid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_product.startDate
     *
     * @return the value of rd_product.startDate
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Date getStartdate() {
        return startdate;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_product.startDate
     *
     * @param startdate the value for rd_product.startDate
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_product.endDate
     *
     * @return the value of rd_product.endDate
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Date getEnddate() {
        return enddate;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_product.endDate
     *
     * @param enddate the value for rd_product.endDate
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_product.unPassReason
     *
     * @return the value of rd_product.unPassReason
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getUnpassreason() {
        return unpassreason;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_product.unPassReason
     *
     * @param unpassreason the value for rd_product.unPassReason
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setUnpassreason(String unpassreason) {
        this.unpassreason = unpassreason == null ? null : unpassreason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_product.isAllCheckOK
     *
     * @return the value of rd_product.isAllCheckOK
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Integer getIsallcheckok() {
        return isallcheckok;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_product.isAllCheckOK
     *
     * @param isallcheckok the value for rd_product.isAllCheckOK
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setIsallcheckok(Integer isallcheckok) {
        this.isallcheckok = isallcheckok;
    }
    
    public Integer getOfflineReason() {
		return offlineReason;
	}
	public void setOfflineReason(Integer offlineReason) {
		this.offlineReason = offlineReason;
	}
	
	public Date getUnsaleDateTime() {
		return unsaleDateTime;
	}
	public void setUnsaleDateTime(Date unsaleDateTime) {
		this.unsaleDateTime = unsaleDateTime;
	}
	
}