package com.expocms.server.db.model;

public class RdPrivilege {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_privilege.ids
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String ids;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_privilege.name
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_privilege.seq
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String seq;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_privilege.ids
     *
     * @return the value of rd_privilege.ids
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getIds() {
        return ids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_privilege.ids
     *
     * @param ids the value for rd_privilege.ids
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setIds(String ids) {
        this.ids = ids == null ? null : ids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_privilege.name
     *
     * @return the value of rd_privilege.name
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_privilege.name
     *
     * @param name the value for rd_privilege.name
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_privilege.seq
     *
     * @return the value of rd_privilege.seq
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_privilege.seq
     *
     * @param seq the value for rd_privilege.seq
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setSeq(String seq) {
        this.seq = seq == null ? null : seq.trim();
    }
}