package com.expocms.server.db.model;

public class RdPrivilegeWithBLOBs extends RdPrivilege {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_privilege.parentId
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_privilege.roleId
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_privilege.children
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String children;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_privilege.parentId
     *
     * @return the value of rd_privilege.parentId
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_privilege.parentId
     *
     * @param parentid the value for rd_privilege.parentId
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setParentid(String parentid) {
        this.parentid = parentid == null ? null : parentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_privilege.roleId
     *
     * @return the value of rd_privilege.roleId
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_privilege.roleId
     *
     * @param roleid the value for rd_privilege.roleId
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setRoleid(String roleid) {
        this.roleid = roleid == null ? null : roleid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_privilege.children
     *
     * @return the value of rd_privilege.children
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getChildren() {
        return children;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_privilege.children
     *
     * @param children the value for rd_privilege.children
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setChildren(String children) {
        this.children = children == null ? null : children.trim();
    }
}