package com.expocms.server.db.model;

import java.util.Date;

public class RdPushmessage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_pushmessage.ids
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String ids;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_pushmessage.time
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_pushmessage.total
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Integer total;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_pushmessage.ids
     *
     * @return the value of rd_pushmessage.ids
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getIds() {
        return ids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_pushmessage.ids
     *
     * @param ids the value for rd_pushmessage.ids
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setIds(String ids) {
        this.ids = ids == null ? null : ids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_pushmessage.time
     *
     * @return the value of rd_pushmessage.time
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_pushmessage.time
     *
     * @param time the value for rd_pushmessage.time
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_pushmessage.total
     *
     * @return the value of rd_pushmessage.total
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Integer getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_pushmessage.total
     *
     * @param total the value for rd_pushmessage.total
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setTotal(Integer total) {
        this.total = total;
    }
}