package com.expocms.server.db.model;

public class RdQaWithBLOBs extends RdQa {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_qa.question
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String question;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_qa.answer
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String answer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_qa.question
     *
     * @return the value of rd_qa.question
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getQuestion() {
        return question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_qa.question
     *
     * @param question the value for rd_qa.question
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setQuestion(String question) {
        this.question = question == null ? null : question.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_qa.answer
     *
     * @return the value of rd_qa.answer
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_qa.answer
     *
     * @param answer the value for rd_qa.answer
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }
}