package com.expocms.server.db.model;

import java.util.Date;

public class RdRepayorder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_repayorder.ids
     *
     * @mbggenerated Fri Oct 02 20:39:17 CST 2015
     */
    private String ids;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_repayorder.productId
     *
     * @mbggenerated Fri Oct 02 20:39:17 CST 2015
     */
    private String productid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_repayorder.productNo
     *
     * @mbggenerated Fri Oct 02 20:39:17 CST 2015
     */
    private String productno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_repayorder.assignId
     *
     * @mbggenerated Fri Oct 02 20:39:17 CST 2015
     */
    private String assignid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_repayorder.assignNo
     *
     * @mbggenerated Fri Oct 02 20:39:17 CST 2015
     */
    private String assignno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_repayorder.orderId
     *
     * @mbggenerated Fri Oct 02 20:39:17 CST 2015
     */
    private String orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_repayorder.orderNo
     *
     * @mbggenerated Fri Oct 02 20:39:17 CST 2015
     */
    private String orderno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_repayorder.appUserId
     *
     * @mbggenerated Fri Oct 02 20:39:17 CST 2015
     */
    private String appuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_repayorder.appUserName
     *
     * @mbggenerated Fri Oct 02 20:39:17 CST 2015
     */
    private String appusername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_repayorder.transferTime
     *
     * @mbggenerated Fri Oct 02 20:39:17 CST 2015
     */
    private Date transfertime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_repayorder.type
     *
     * @mbggenerated Fri Oct 02 20:39:17 CST 2015
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_repayorder.amount
     *
     * @mbggenerated Fri Oct 02 20:39:17 CST 2015
     */
    private Long amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_repayorder.payAmount
     *
     * @mbggenerated Fri Oct 02 20:39:17 CST 2015
     */
    private Long payamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_repayorder.giftAmount
     *
     * @mbggenerated Fri Oct 02 20:39:17 CST 2015
     */
    private Long giftamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_repayorder.resultMsg
     *
     * @mbggenerated Fri Oct 02 20:39:17 CST 2015
     */
    private String resultmsg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_repayorder.ids
     *
     * @return the value of rd_repayorder.ids
     *
     * @mbggenerated Fri Oct 02 20:39:17 CST 2015
     */
    public String getIds() {
        return ids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_repayorder.ids
     *
     * @param ids the value for rd_repayorder.ids
     *
     * @mbggenerated Fri Oct 02 20:39:17 CST 2015
     */
    public void setIds(String ids) {
        this.ids = ids == null ? null : ids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_repayorder.productId
     *
     * @return the value of rd_repayorder.productId
     *
     * @mbggenerated Fri Oct 02 20:39:17 CST 2015
     */
    public String getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_repayorder.productId
     *
     * @param productid the value for rd_repayorder.productId
     *
     * @mbggenerated Fri Oct 02 20:39:17 CST 2015
     */
    public void setProductid(String productid) {
        this.productid = productid == null ? null : productid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_repayorder.productNo
     *
     * @return the value of rd_repayorder.productNo
     *
     * @mbggenerated Fri Oct 02 20:39:17 CST 2015
     */
    public String getProductno() {
        return productno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_repayorder.productNo
     *
     * @param productno the value for rd_repayorder.productNo
     *
     * @mbggenerated Fri Oct 02 20:39:17 CST 2015
     */
    public void setProductno(String productno) {
        this.productno = productno == null ? null : productno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_repayorder.assignId
     *
     * @return the value of rd_repayorder.assignId
     *
     * @mbggenerated Fri Oct 02 20:39:17 CST 2015
     */
    public String getAssignid() {
        return assignid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_repayorder.assignId
     *
     * @param assignid the value for rd_repayorder.assignId
     *
     * @mbggenerated Fri Oct 02 20:39:17 CST 2015
     */
    public void setAssignid(String assignid) {
        this.assignid = assignid == null ? null : assignid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_repayorder.assignNo
     *
     * @return the value of rd_repayorder.assignNo
     *
     * @mbggenerated Fri Oct 02 20:39:17 CST 2015
     */
    public String getAssignno() {
        return assignno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_repayorder.assignNo
     *
     * @param assignno the value for rd_repayorder.assignNo
     *
     * @mbggenerated Fri Oct 02 20:39:17 CST 2015
     */
    public void setAssignno(String assignno) {
        this.assignno = assignno == null ? null : assignno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_repayorder.orderId
     *
     * @return the value of rd_repayorder.orderId
     *
     * @mbggenerated Fri Oct 02 20:39:17 CST 2015
     */
    public String getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_repayorder.orderId
     *
     * @param orderid the value for rd_repayorder.orderId
     *
     * @mbggenerated Fri Oct 02 20:39:17 CST 2015
     */
    public void setOrderid(String orderid) {
        this.orderid = orderid == null ? null : orderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_repayorder.orderNo
     *
     * @return the value of rd_repayorder.orderNo
     *
     * @mbggenerated Fri Oct 02 20:39:17 CST 2015
     */
    public String getOrderno() {
        return orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_repayorder.orderNo
     *
     * @param orderno the value for rd_repayorder.orderNo
     *
     * @mbggenerated Fri Oct 02 20:39:17 CST 2015
     */
    public void setOrderno(String orderno) {
        this.orderno = orderno == null ? null : orderno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_repayorder.appUserId
     *
     * @return the value of rd_repayorder.appUserId
     *
     * @mbggenerated Fri Oct 02 20:39:17 CST 2015
     */
    public String getAppuserid() {
        return appuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_repayorder.appUserId
     *
     * @param appuserid the value for rd_repayorder.appUserId
     *
     * @mbggenerated Fri Oct 02 20:39:17 CST 2015
     */
    public void setAppuserid(String appuserid) {
        this.appuserid = appuserid == null ? null : appuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_repayorder.appUserName
     *
     * @return the value of rd_repayorder.appUserName
     *
     * @mbggenerated Fri Oct 02 20:39:17 CST 2015
     */
    public String getAppusername() {
        return appusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_repayorder.appUserName
     *
     * @param appusername the value for rd_repayorder.appUserName
     *
     * @mbggenerated Fri Oct 02 20:39:17 CST 2015
     */
    public void setAppusername(String appusername) {
        this.appusername = appusername == null ? null : appusername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_repayorder.transferTime
     *
     * @return the value of rd_repayorder.transferTime
     *
     * @mbggenerated Fri Oct 02 20:39:17 CST 2015
     */
    public Date getTransfertime() {
        return transfertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_repayorder.transferTime
     *
     * @param transfertime the value for rd_repayorder.transferTime
     *
     * @mbggenerated Fri Oct 02 20:39:17 CST 2015
     */
    public void setTransfertime(Date transfertime) {
        this.transfertime = transfertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_repayorder.type
     *
     * @return the value of rd_repayorder.type
     *
     * @mbggenerated Fri Oct 02 20:39:17 CST 2015
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_repayorder.type
     *
     * @param type the value for rd_repayorder.type
     *
     * @mbggenerated Fri Oct 02 20:39:17 CST 2015
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_repayorder.amount
     *
     * @return the value of rd_repayorder.amount
     *
     * @mbggenerated Fri Oct 02 20:39:17 CST 2015
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_repayorder.amount
     *
     * @param amount the value for rd_repayorder.amount
     *
     * @mbggenerated Fri Oct 02 20:39:17 CST 2015
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_repayorder.payAmount
     *
     * @return the value of rd_repayorder.payAmount
     *
     * @mbggenerated Fri Oct 02 20:39:17 CST 2015
     */
    public Long getPayamount() {
        return payamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_repayorder.payAmount
     *
     * @param payamount the value for rd_repayorder.payAmount
     *
     * @mbggenerated Fri Oct 02 20:39:17 CST 2015
     */
    public void setPayamount(Long payamount) {
        this.payamount = payamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_repayorder.giftAmount
     *
     * @return the value of rd_repayorder.giftAmount
     *
     * @mbggenerated Fri Oct 02 20:39:17 CST 2015
     */
    public Long getGiftamount() {
        return giftamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_repayorder.giftAmount
     *
     * @param giftamount the value for rd_repayorder.giftAmount
     *
     * @mbggenerated Fri Oct 02 20:39:17 CST 2015
     */
    public void setGiftamount(Long giftamount) {
        this.giftamount = giftamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_repayorder.resultMsg
     *
     * @return the value of rd_repayorder.resultMsg
     *
     * @mbggenerated Fri Oct 02 20:39:17 CST 2015
     */
    public String getResultmsg() {
        return resultmsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_repayorder.resultMsg
     *
     * @param resultmsg the value for rd_repayorder.resultMsg
     *
     * @mbggenerated Fri Oct 02 20:39:17 CST 2015
     */
    public void setResultmsg(String resultmsg) {
        this.resultmsg = resultmsg == null ? null : resultmsg.trim();
    }
}