package com.expocms.server.db.model;

public class RdRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_role.ids
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String ids;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_role.name
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_role.privIds
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String privids;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_role.privNames
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String privnames;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_role.createTime
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Long createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_role.ids
     *
     * @return the value of rd_role.ids
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getIds() {
        return ids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_role.ids
     *
     * @param ids the value for rd_role.ids
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setIds(String ids) {
        this.ids = ids == null ? null : ids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_role.name
     *
     * @return the value of rd_role.name
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_role.name
     *
     * @param name the value for rd_role.name
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_role.privIds
     *
     * @return the value of rd_role.privIds
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getPrivids() {
        return privids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_role.privIds
     *
     * @param privids the value for rd_role.privIds
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setPrivids(String privids) {
        this.privids = privids == null ? null : privids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_role.privNames
     *
     * @return the value of rd_role.privNames
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getPrivnames() {
        return privnames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_role.privNames
     *
     * @param privnames the value for rd_role.privNames
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setPrivnames(String privnames) {
        this.privnames = privnames == null ? null : privnames.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_role.createTime
     *
     * @return the value of rd_role.createTime
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Long getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_role.createTime
     *
     * @param createtime the value for rd_role.createTime
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setCreatetime(Long createtime) {
        this.createtime = createtime;
    }
}