package com.expocms.server.db.model;

import java.util.Date;

public class RdSystemlog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_systemlog.ids
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String ids;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_systemlog.createTime
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_systemlog.operatorName
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private String operatorname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rd_systemlog.status
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    private Boolean status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_systemlog.ids
     *
     * @return the value of rd_systemlog.ids
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getIds() {
        return ids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_systemlog.ids
     *
     * @param ids the value for rd_systemlog.ids
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setIds(String ids) {
        this.ids = ids == null ? null : ids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_systemlog.createTime
     *
     * @return the value of rd_systemlog.createTime
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_systemlog.createTime
     *
     * @param createtime the value for rd_systemlog.createTime
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_systemlog.operatorName
     *
     * @return the value of rd_systemlog.operatorName
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public String getOperatorname() {
        return operatorname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_systemlog.operatorName
     *
     * @param operatorname the value for rd_systemlog.operatorName
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setOperatorname(String operatorname) {
        this.operatorname = operatorname == null ? null : operatorname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rd_systemlog.status
     *
     * @return the value of rd_systemlog.status
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rd_systemlog.status
     *
     * @param status the value for rd_systemlog.status
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }
}