package com.expocms.server.db.dao;

import com.expocms.server.db.model.RdActivitygiftStat;

public interface RdActivitygiftStatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_activitygift_stat
     *
     * @mbggenerated Sun Oct 04 14:55:06 CST 2015
     */
    int deleteByPrimaryKey(String ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_activitygift_stat
     *
     * @mbggenerated Sun Oct 04 14:55:06 CST 2015
     */
    int insert(RdActivitygiftStat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_activitygift_stat
     *
     * @mbggenerated Sun Oct 04 14:55:06 CST 2015
     */
    int insertSelective(RdActivitygiftStat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_activitygift_stat
     *
     * @mbggenerated Sun Oct 04 14:55:06 CST 2015
     */
    RdActivitygiftStat selectByPrimaryKey(String ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_activitygift_stat
     *
     * @mbggenerated Sun Oct 04 14:55:06 CST 2015
     */
    int updateByPrimaryKeySelective(RdActivitygiftStat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_activitygift_stat
     *
     * @mbggenerated Sun Oct 04 14:55:06 CST 2015
     */
    int updateByPrimaryKey(RdActivitygiftStat record);
}