package com.expocms.server.db.dao;

import com.expocms.server.db.model.RdActivitygift;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface RdActivitygiftMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_activitygift
     *
     * @mbggenerated Mon Sep 21 01:18:13 CST 2015
     */
    int deleteByPrimaryKey(String ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_activitygift
     *
     * @mbggenerated Mon Sep 21 01:18:13 CST 2015
     */
    int insert(RdActivitygift record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_activitygift
     *
     * @mbggenerated Mon Sep 21 01:18:13 CST 2015
     */
    int insertSelective(RdActivitygift record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_activitygift
     *
     * @mbggenerated Mon Sep 21 01:18:13 CST 2015
     */
    RdActivitygift selectByPrimaryKey(String ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_activitygift
     *
     * @mbggenerated Mon Sep 21 01:18:13 CST 2015
     */
    int updateByPrimaryKeySelective(RdActivitygift record);

    /**
//     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_activitygift
     *
     * @mbggenerated Mon Sep 21 01:18:13 CST 2015
     */
    int updateByPrimaryKey(RdActivitygift record);

    @Select("select * from rd_activitygift where expireDate >= sysdate() and isActivated = 1")
    List<RdActivitygift> queryUnExpiredGift();

    @Select("select * from rd_activitygift where activateDate >= sysdate() and isActivated = 0")
    List<RdActivitygift> queryUnActivatedGift();

    List<RdActivitygift> queryByIds(@Param("giftIds")List<String> giftIds);
}