package com.expocms.server.db.dao;

import com.expocms.server.db.model.RdAdvice;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface RdAdviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_advice
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int insert(RdAdvice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_advice
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int insertSelective(RdAdvice record);

    List<RdAdvice> queryMyAdvice(@Param("userId") String userId,@Param("pageStart")int pageStart,@Param("pageCount")int pageCount);

    @Select(value="select * from rd_advice where appUserId = #{userId} order by time desc LIMIT #{pageStart} , #{pageCount}")
	List<RdAdvice> queryMyAdviceExt(@Param("userId") String userId,@Param("pageStart")int pageStart,@Param("pageCount")int pageCount);
}