package com.expocms.server.db.dao;

import org.apache.ibatis.annotations.Select;
import org.springframework.stereotype.Repository;

import com.expocms.server.db.model.RdAppuserOrders;
@Repository
public interface RdAppuserOrdersMapper {
	@Select(value="SELECT count(1) FROM rd_appuser_orders WHERE ids_user= #{userid_}")
	int getOrderNumOfCurrentUser(String userid_);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_appuser_orders
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int deleteByPrimaryKey(String ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_appuser_orders
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int insert(RdAppuserOrders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_appuser_orders
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int insertSelective(RdAppuserOrders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_appuser_orders
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    RdAppuserOrders selectByPrimaryKey(String ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_appuser_orders
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int updateByPrimaryKeySelective(RdAppuserOrders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_appuser_orders
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int updateByPrimaryKey(RdAppuserOrders record);
}