package com.expocms.server.db.dao;

import org.springframework.stereotype.Repository;

import com.expocms.server.db.model.RdAppuserlog;
@Repository
public interface RdAppuserlogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_appuserlog
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int insert(RdAppuserlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_appuserlog
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int insertSelective(RdAppuserlog record);
}