package com.expocms.server.db.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.springframework.stereotype.Repository;

import com.expocms.server.db.model.RdAppuser;
import com.expocms.server.response.types.impl.CurrentBuyUser;

@Repository
public interface RdAppuserMapper {
	

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * rd_appuser
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int deleteByPrimaryKey (String ids);


    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * rd_appuser
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int insert (RdAppuser record);


    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * rd_appuser
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int insertSelective (RdAppuser record);


    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * rd_appuser
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    RdAppuser selectByPrimaryKey (String ids);

    @Select(value="select * from rd_appuser where phone = #{phone_}")
    RdAppuser selectByPhone (String phone_);


    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * rd_appuser
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int updateByPrimaryKeySelective (RdAppuser record);


    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * rd_appuser
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs (RdAppuser record);


    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * rd_appuser
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int updateByPrimaryKey (RdAppuser record);

    @Select ("select * from rd_appuser where idcard = #{idcard_}")
    RdAppuser selectByIdCard (String idcard_);
    
    @Select ("select * from rd_appuser where ids = #{userId} ")
    RdAppuser selectByUserId (String userId);

    @Select ("select count(*) from rd_appuser")
    int getAllUser ();


    @Select ("select count(*) from rd_appuser where phone = #{phone}")
    int getAllUserByPhone (String phone);
    
    
    int updateByIds(RdAppuser record);
    int updateBankInfoByIds(RdAppuser record);
    int updateTokenByIds(RdAppuser record);
    int updateFixedGiftByIds(RdAppuser record);
    int updateActivityGiftByIds(RdAppuser record);
    int updatePwdBlockInfoByIds(RdAppuser record);
    int resetPwdByIds(RdAppuser record);
    int updateCommissionByIds(RdAppuser record);
    
    
//    @Select ("select  count(1) from rd_order o where o.productIds = #{0} ")
//    int currentPeriodBuyUserNumber(String productId);
    
    @Select ("select o.appUserPhone as phoneNo, o.orderCreateTime as buyTimeDB, o.amount as buyMoney from rd_order o where o.productIds = #{0} order by o.orderCreateTime desc limit #{1}, #{2}")
    List<CurrentBuyUser> currentPeriodBuy(String productId, int min, int max);
    
    @Select("select a.ids as ids, a.phone as phone, a.userName as username, a.sex as sex from rd_appuser a where a.activitygift like CONCAT('%',#{ids},'%') ")
    RdAppuser queryAppUserByActivityPackage(@Param("ids")String ids);
    
    @Select("select a.ids as ids, a.phone as phone, a.userName as username, a.sex as sex from rd_appuser a where a.fixedgift like CONCAT('%',#{ids},'%')")
    RdAppuser queryAppUserByFixedPackage(@Param("ids")String ids);

}
