package com.expocms.server.db.dao;

import org.springframework.stereotype.Repository;

import com.expocms.server.db.model.RdAppuserBonus;
@Repository
public interface RdAppuserBonusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_appuser_bonus
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int deleteByPrimaryKey(String ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_appuser_bonus
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int insert(RdAppuserBonus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_appuser_bonus
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int insertSelective(RdAppuserBonus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_appuser_bonus
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    RdAppuserBonus selectByPrimaryKey(String ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_appuser_bonus
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int updateByPrimaryKeySelective(RdAppuserBonus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_appuser_bonus
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int updateByPrimaryKey(RdAppuserBonus record);
}