package com.expocms.server.db.dao;

import org.springframework.stereotype.Repository;

import com.expocms.server.db.model.RdAppuserinformationmodlog;
import com.expocms.server.db.model.RdAppuserinformationmodlogWithBLOBs;
@Repository
public interface RdAppuserinformationmodlogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_appuserinformationmodlog
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int deleteByPrimaryKey(String ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_appuserinformationmodlog
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int insert(RdAppuserinformationmodlogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_appuserinformationmodlog
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int insertSelective(RdAppuserinformationmodlogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_appuserinformationmodlog
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    RdAppuserinformationmodlogWithBLOBs selectByPrimaryKey(String ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_appuserinformationmodlog
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int updateByPrimaryKeySelective(RdAppuserinformationmodlogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_appuserinformationmodlog
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(RdAppuserinformationmodlogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_appuserinformationmodlog
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int updateByPrimaryKey(RdAppuserinformationmodlog record);
}