package com.expocms.server.db.dao;

import com.expocms.server.db.model.RdCouponGroup;
import com.expocms.server.db.model.RdCouponGroupExt;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
@Repository
public interface RdCouponGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_coupon_group
     *
     * @mbggenerated Sun Aug 16 01:14:17 CST 2015
     */
    int countByExample(RdCouponGroupExt example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_coupon_group
     *
     * @mbggenerated Sun Aug 16 01:14:17 CST 2015
     */
    int deleteByExample(RdCouponGroupExt example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_coupon_group
     *
     * @mbggenerated Sun Aug 16 01:14:17 CST 2015
     */
    int deleteByPrimaryKey(String ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_coupon_group
     *
     * @mbggenerated Sun Aug 16 01:14:17 CST 2015
     */
    int insert(RdCouponGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_coupon_group
     *
     * @mbggenerated Sun Aug 16 01:14:17 CST 2015
     */
    int insertSelective(RdCouponGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_coupon_group
     *
     * @mbggenerated Sun Aug 16 01:14:17 CST 2015
     */
    List<RdCouponGroup> selectByExample(RdCouponGroupExt example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_coupon_group
     *
     * @mbggenerated Sun Aug 16 01:14:17 CST 2015
     */
    RdCouponGroup selectByPrimaryKey(String ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_coupon_group
     *
     * @mbggenerated Sun Aug 16 01:14:17 CST 2015
     */
    int updateByExampleSelective(@Param("record") RdCouponGroup record, @Param("example") RdCouponGroupExt example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_coupon_group
     *
     * @mbggenerated Sun Aug 16 01:14:17 CST 2015
     */
    int updateByExample(@Param("record") RdCouponGroup record, @Param("example") RdCouponGroupExt example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_coupon_group
     *
     * @mbggenerated Sun Aug 16 01:14:17 CST 2015
     */
    int updateByPrimaryKeySelective(RdCouponGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_coupon_group
     *
     * @mbggenerated Sun Aug 16 01:14:17 CST 2015
     */
    int updateByPrimaryKey(RdCouponGroup record);
}