package com.expocms.server.db.dao;

import org.springframework.stereotype.Repository;

import com.expocms.server.db.model.RdConsultant;
@Repository
public interface RdConsultantMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_consultant
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int insert(RdConsultant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_consultant
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int insertSelective(RdConsultant record);
}