package com.expocms.server.db.dao;

import com.expocms.server.db.model.RdCoupon;
import com.expocms.server.db.model.RdCouponExt;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
@Repository
public interface RdCouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_coupon
     *
     * @mbggenerated Sun Aug 16 01:14:17 CST 2015
     */
    int countByExample(RdCouponExt example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_coupon
     *
     * @mbggenerated Sun Aug 16 01:14:17 CST 2015
     */
    int deleteByExample(RdCouponExt example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_coupon
     *
     * @mbggenerated Sun Aug 16 01:14:17 CST 2015
     */
    int deleteByPrimaryKey(String ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_coupon
     *
     * @mbggenerated Sun Aug 16 01:14:17 CST 2015
     */
    int insert(RdCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_coupon
     *
     * @mbggenerated Sun Aug 16 01:14:17 CST 2015
     */
    int insertSelective(RdCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_coupon
     *
     * @mbggenerated Sun Aug 16 01:14:17 CST 2015
     */
    List<RdCoupon> selectByExample(RdCouponExt example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_coupon
     *
     * @mbggenerated Sun Aug 16 01:14:17 CST 2015
     */
    RdCoupon selectByPrimaryKey(String ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_coupon
     *
     * @mbggenerated Sun Aug 16 01:14:17 CST 2015
     */
    int updateByExampleSelective(@Param("record") RdCoupon record, @Param("example") RdCouponExt example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_coupon
     *
     * @mbggenerated Sun Aug 16 01:14:17 CST 2015
     */
    int updateByExample(@Param("record") RdCoupon record, @Param("example") RdCouponExt example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_coupon
     *
     * @mbggenerated Sun Aug 16 01:14:17 CST 2015
     */
    int updateByPrimaryKeySelective(RdCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_coupon
     *
     * @mbggenerated Sun Aug 16 01:14:17 CST 2015
     */
    int updateByPrimaryKey(RdCoupon record);
}