package com.expocms.server.db.dao;

import org.springframework.stereotype.Repository;

import com.expocms.server.db.model.RdDepartment;
@Repository
public interface RdDepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_department
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int insert(RdDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_department
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int insertSelective(RdDepartment record);
}