package com.expocms.server.db.dao;

import java.util.List;

import org.apache.ibatis.annotations.Select;

import com.expocms.server.db.model.RdFixedgift;
import org.springframework.stereotype.Repository;

@Repository
public interface RdFixedgiftMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_fixedgift
     *
     * @mbggenerated Sun Sep 20 22:05:56 CST 2015
     */
    int deleteByPrimaryKey(String ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_fixedgift
     *
     * @mbggenerated Sun Sep 20 22:05:56 CST 2015
     */
    int insert(RdFixedgift record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_fixedgift
     *
     * @mbggenerated Sun Sep 20 22:05:56 CST 2015
     */
    int insertSelective(RdFixedgift record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_fixedgift
     *
     * @mbggenerated Sun Sep 20 22:05:56 CST 2015
     */
    RdFixedgift selectByPrimaryKey(String ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_fixedgift
     *
     * @mbggenerated Sun Sep 20 22:05:56 CST 2015
     */
    int updateByPrimaryKeySelective(RdFixedgift record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_fixedgift
     *
     * @mbggenerated Sun Sep 20 22:05:56 CST 2015
     */
    int updateByPrimaryKey(RdFixedgift record);
    
    @Select (value="select * from rd_fixedgift where status = 1 and type = #{0}")
    RdFixedgift selectByType(String type);
    
    @Select (value="select * from rd_fixedgift where status = 1")
    List<RdFixedgift> getAllFixedGifts();
}