package com.expocms.server.db.dao;

import org.springframework.stereotype.Repository;

import com.expocms.server.db.model.RdOperator;
@Repository
public interface RdOperatorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_operator
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int deleteByPrimaryKey(String ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_operator
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int insert(RdOperator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_operator
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int insertSelective(RdOperator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_operator
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    RdOperator selectByPrimaryKey(String ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_operator
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int updateByPrimaryKeySelective(RdOperator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_operator
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int updateByPrimaryKey(RdOperator record);
}