package com.expocms.server.db.dao;

import org.springframework.stereotype.Repository;

import com.expocms.server.db.model.RdPaymentRefound;
@Repository
public interface RdPaymentRefoundMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_payment_refound
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int deleteByPrimaryKey(String ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_payment_refound
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int insert(RdPaymentRefound record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_payment_refound
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int insertSelective(RdPaymentRefound record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_payment_refound
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    RdPaymentRefound selectByPrimaryKey(String ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_payment_refound
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int updateByPrimaryKeySelective(RdPaymentRefound record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_payment_refound
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int updateByPrimaryKey(RdPaymentRefound record);
}