package com.expocms.server.db.dao;

import org.springframework.stereotype.Repository;

import com.expocms.server.db.model.RdPaymentRecord;
@Repository
public interface RdPaymentRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_payment_record
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int deleteByPrimaryKey(String ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_payment_record
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int insert(RdPaymentRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_payment_record
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int insertSelective(RdPaymentRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_payment_record
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    RdPaymentRecord selectByPrimaryKey(String ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_payment_record
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int updateByPrimaryKeySelective(RdPaymentRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_payment_record
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int updateByPrimaryKey(RdPaymentRecord record);
}