package com.expocms.server.db.dao;

import org.springframework.stereotype.Repository;

import com.expocms.server.db.model.RdPayment;
@Repository
public interface RdPaymentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_payment
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int deleteByPrimaryKey(String ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_payment
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int insert(RdPayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_payment
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int insertSelective(RdPayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_payment
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    RdPayment selectByPrimaryKey(String ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_payment
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int updateByPrimaryKeySelective(RdPayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_payment
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int updateByPrimaryKey(RdPayment record);
}