package com.expocms.server.db.dao;

import org.springframework.stereotype.Repository;

import com.expocms.server.db.model.RdPushmessage;
import com.expocms.server.db.model.RdPushmessageWithBLOBs;
@Repository
public interface RdPushmessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_pushmessage
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int deleteByPrimaryKey(String ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_pushmessage
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int insert(RdPushmessageWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_pushmessage
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int insertSelective(RdPushmessageWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_pushmessage
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    RdPushmessageWithBLOBs selectByPrimaryKey(String ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_pushmessage
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int updateByPrimaryKeySelective(RdPushmessageWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_pushmessage
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(RdPushmessageWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_pushmessage
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int updateByPrimaryKey(RdPushmessage record);
}