package com.expocms.server.db.dao;

import org.springframework.stereotype.Repository;

import com.expocms.server.db.model.RdQaWithBLOBs;
@Repository
public interface RdQaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_qa
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int insert(RdQaWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_qa
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int insertSelective(RdQaWithBLOBs record);
}