package com.expocms.server.db.dao;

import com.expocms.server.db.model.RdRepayorder;

public interface RdRepayorderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_repayorder
     *
     * @mbggenerated Fri Oct 02 20:39:17 CST 2015
     */
    int insert(RdRepayorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_repayorder
     *
     * @mbggenerated Fri Oct 02 20:39:17 CST 2015
     */
    int insertSelective(RdRepayorder record);
}