package com.expocms.server.db.dao;

import org.springframework.stereotype.Repository;

import com.expocms.server.db.model.RdSystemlog;
import com.expocms.server.db.model.RdSystemlogWithBLOBs;
@Repository
public interface RdSystemlogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_systemlog
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int deleteByPrimaryKey(String ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_systemlog
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int insert(RdSystemlogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_systemlog
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int insertSelective(RdSystemlogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_systemlog
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    RdSystemlogWithBLOBs selectByPrimaryKey(String ids);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_systemlog
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int updateByPrimaryKeySelective(RdSystemlogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_systemlog
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(RdSystemlogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rd_systemlog
     *
     * @mbggenerated Sun Sep 13 15:37:00 CST 2015
     */
    int updateByPrimaryKey(RdSystemlog record);
}